hikoboshi_modules_sources = files(
  'esm2/esm2.cpp',
  'esm2/esm2_scalar.cpp',
  'ffn/ffn_layer_scalar.cpp',
  'mpnn/decode_order_scalar.cpp',
  'mpnn/decoder_layer_scalar.cpp',
  'mpnn/edge_rbf_features_scalar.cpp',
  'mpnn/ffn_layer_scalar.cpp',
  'mpnn/inverse_fold_scalar.cpp',
  'mpnn/message_layer_scalar.cpp',
  'mpnn/mpnn.cpp',
  'mpnn/mpnn_scalar.cpp',
  'mpnn/proteinmpnn_encoder_scalar.cpp',
  'mpnn/sampler_scalar.cpp',
  'similarity/similarity.cpp',
  'similarity/similarity_scalar.cpp',
  'soft_smith_waterman.cpp',
  'transformer/attention_scalar.cpp',
  'modules_entry.cpp',
)
