// Real PyTorch ESM2-8M parity test (mirror of mpnn64_real_parity).
//
// Loads a precomputed PyTorch ESM2-8M golden activation fixture
// (`tests/cpp/data/esm2_pytorch_goldens.npz`) generated from Casey's
// joint MLM + alignment fine-tuned checkpoint via
// `scripts/esm2_pytorch_goldens.py`. Runs Hikoboshi's
// `esm2_forward_scalar` on the same input token span using the embedded
// Hikoboshi-ESM2-8M weights and compares output embeddings to the golden
// element-by-element.
//
// Tolerance follows the public parity contract:
//   - strict-mode build (HIKOBOSHI_GEMM_PARITY_MODE=strict): max abs <= 1e-5
//   - fast-mode build (default): max abs <= 1e-4
//
// On a regression the test prints concrete max-abs and L2 deltas plus
// the per-row max-abs to make bisection easier; per the packet contract
// the tolerance is never relaxed silently to make the test pass — a real
// Hikoboshi/PyTorch divergence is the signal this test exists to catch.
//
// The fixture is committed to the repo so the test runs unconditionally;
// the goldens are regenerated by re-running the Python script when the
// embedded weights or the reference architecture change.

#include <hikoboshi/algorithms/pairwise.hpp>
#include <hikoboshi/modules/detail/esm2_layers.hpp>
#include <hikoboshi/modules/esm2.hpp>
#include <hikoboshi/universal/span.hpp>
#include <hikoboshi/universal/status.hpp>
#include <hikoboshi/universal/weights.hpp>
#include <hikoboshi/weights/provider.hpp>

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <string>
#include <string_view>
#include <vector>

namespace hiko = hikoboshi::algorithms;
namespace hiko_m = hikoboshi::modules;
namespace hiko_u = hikoboshi::universal;
namespace hiko_w = hikoboshi::weights;

namespace {

constexpr std::size_t kEsm2HiddenDim = 320;
constexpr std::size_t kEsm2LayerCount = 6;
constexpr std::size_t kEsm2HeadCount = 20;
constexpr std::size_t kEsm2HeadDim = kEsm2HiddenDim / kEsm2HeadCount;
constexpr std::size_t kEsm2FfnHiddenDim = 1280;
constexpr std::size_t kEsm2VocabSize = 29;
constexpr std::size_t kEsm2MaxSequenceLength = 1024;

[[noreturn]] void fail(const std::string& detail) {
  std::fprintf(stderr, "esm2_pytorch_real_parity: %s\n", detail.c_str());
  std::exit(1);
}

float strict_tolerance() noexcept { return 1.0e-5F; }
float fast_tolerance() noexcept { return 1.0e-4F; }

float active_tolerance() noexcept {
  const char* mode = std::getenv("HIKOBOSHI_GEMM_PARITY_MODE");
  if (mode != nullptr && std::string_view{mode} == "strict") {
    return strict_tolerance();
  }
  return fast_tolerance();
}

// === Minimal ZIP_STORED NPZ reader =========================================
//
// numpy.savez writes a ZIP archive of .npy files with method=STORED
// (no DEFLATE). We walk the local-file-header records, lift the named
// .npy payload, then parse the .npy descriptor enough to verify dtype
// and shape. We never decompress because savez never compresses.

struct NpyEntry {
  std::string dtype;        // e.g. "<f4", "<i4"
  std::vector<std::size_t> shape;
  std::vector<unsigned char> data;
};

std::uint16_t read_u16_le(const unsigned char* bytes) noexcept {
  return static_cast<std::uint16_t>(bytes[0]) |
         (static_cast<std::uint16_t>(bytes[1]) << 8);
}

std::uint32_t read_u32_le(const unsigned char* bytes) noexcept {
  return static_cast<std::uint32_t>(bytes[0]) |
         (static_cast<std::uint32_t>(bytes[1]) << 8) |
         (static_cast<std::uint32_t>(bytes[2]) << 16) |
         (static_cast<std::uint32_t>(bytes[3]) << 24);
}

std::uint64_t read_u64_le(const unsigned char* bytes) noexcept {
  std::uint64_t lo = read_u32_le(bytes);
  std::uint64_t hi = read_u32_le(bytes + 4);
  return lo | (hi << 32);
}

std::string strip_quotes(std::string_view value) {
  while (!value.empty() && (value.front() == ' ' || value.front() == '\t')) {
    value.remove_prefix(1);
  }
  while (!value.empty() && (value.back() == ' ' || value.back() == '\t')) {
    value.remove_suffix(1);
  }
  if (value.size() >= 2 && (value.front() == '\'' || value.front() == '"') &&
      value.back() == value.front()) {
    return std::string{value.substr(1, value.size() - 2)};
  }
  return std::string{value};
}

std::string find_string_field(const std::string& header,
                              const std::string& key) {
  const std::string needle = "'" + key + "':";
  const std::size_t pos = header.find(needle);
  if (pos == std::string::npos) {
    return std::string{};
  }
  const std::size_t value_start = pos + needle.size();
  std::size_t value_end = header.find(',', value_start);
  if (value_end == std::string::npos) {
    value_end = header.find('}', value_start);
  }
  if (value_end == std::string::npos) {
    return std::string{};
  }
  return strip_quotes(std::string_view{header}.substr(
      value_start, value_end - value_start));
}

std::vector<std::size_t> parse_shape_field(const std::string& header) {
  const std::string needle = "'shape':";
  const std::size_t pos = header.find(needle);
  if (pos == std::string::npos) {
    return {};
  }
  const std::size_t paren_open = header.find('(', pos);
  const std::size_t paren_close = header.find(')', paren_open);
  if (paren_open == std::string::npos || paren_close == std::string::npos ||
      paren_close <= paren_open) {
    return {};
  }
  std::string body = header.substr(paren_open + 1, paren_close - paren_open - 1);
  std::vector<std::size_t> dims;
  std::string token;
  for (char c : body) {
    if (c == ',' || c == ' ' || c == '\t') {
      if (!token.empty()) {
        dims.push_back(static_cast<std::size_t>(std::stoull(token)));
        token.clear();
      }
    } else {
      token.push_back(c);
    }
  }
  if (!token.empty()) {
    dims.push_back(static_cast<std::size_t>(std::stoull(token)));
  }
  return dims;
}

NpyEntry parse_npy(const unsigned char* bytes, std::size_t size) {
  if (size < 10) {
    fail("npy entry truncated below magic+header-len");
  }
  static const unsigned char kMagic[] = {0x93, 'N', 'U', 'M', 'P', 'Y'};
  if (std::memcmp(bytes, kMagic, sizeof(kMagic)) != 0) {
    fail("npy entry has wrong magic");
  }
  const std::uint8_t major = bytes[6];
  std::size_t header_offset = 0;
  std::size_t header_len = 0;
  if (major == 1) {
    header_len = read_u16_le(bytes + 8);
    header_offset = 10;
  } else if (major == 2 || major == 3) {
    if (size < 12) {
      fail("npy v2+ entry truncated");
    }
    header_len = read_u32_le(bytes + 8);
    header_offset = 12;
  } else {
    fail("npy entry has unsupported major version");
  }
  if (header_offset + header_len > size) {
    fail("npy header runs past entry boundary");
  }
  std::string header(reinterpret_cast<const char*>(bytes + header_offset),
                     header_len);
  NpyEntry entry{};
  entry.dtype = find_string_field(header, "descr");
  if (entry.dtype.empty()) {
    fail("npy header missing descr field");
  }
  const std::string fortran = find_string_field(header, "fortran_order");
  if (!fortran.empty() && fortran != "False") {
    fail("npy entry must be C-order");
  }
  entry.shape = parse_shape_field(header);
  const std::size_t data_offset = header_offset + header_len;
  const std::size_t data_bytes = size - data_offset;
  entry.data.assign(bytes + data_offset, bytes + data_offset + data_bytes);
  return entry;
}

void read_npz(const std::filesystem::path& path,
              std::vector<std::pair<std::string, NpyEntry>>& out_entries) {
  std::ifstream in(path, std::ios::binary | std::ios::ate);
  if (!in) {
    fail("could not open npz fixture: " + path.string());
  }
  const std::streamsize size = in.tellg();
  in.seekg(0, std::ios::beg);
  std::vector<unsigned char> bytes(static_cast<std::size_t>(size));
  if (!in.read(reinterpret_cast<char*>(bytes.data()),
               static_cast<std::streamsize>(bytes.size()))) {
    fail("failed reading npz fixture: " + path.string());
  }
  std::size_t cursor = 0;
  while (cursor + 4 <= bytes.size()) {
    if (read_u32_le(bytes.data() + cursor) != 0x04034b50u) {
      break;  // first non-local-header record ends the entry stream
    }
    if (cursor + 30 > bytes.size()) {
      fail("npz local file header truncated");
    }
    const std::uint16_t method = read_u16_le(bytes.data() + cursor + 8);
    if (method != 0) {
      fail("npz fixture must use ZIP_STORED (method=0)");
    }
    std::uint64_t compressed_size =
        read_u32_le(bytes.data() + cursor + 18);
    std::uint64_t uncompressed_size =
        read_u32_le(bytes.data() + cursor + 22);
    const std::uint16_t name_len = read_u16_le(bytes.data() + cursor + 26);
    const std::uint16_t extra_len = read_u16_le(bytes.data() + cursor + 28);
    const std::size_t header_size =
        30 + static_cast<std::size_t>(name_len) + extra_len;
    if (cursor + header_size > bytes.size()) {
      fail("npz local file header + name + extra exceeds archive size");
    }
    // ZIP64: when either 32-bit size field is 0xFFFFFFFF, the real
    // 64-bit values live in the 0x0001 extra-field record. numpy.savez
    // emits ZIP64 entries by default even for small files.
    if (compressed_size == 0xFFFFFFFFull || uncompressed_size == 0xFFFFFFFFull) {
      const unsigned char* extra =
          bytes.data() + cursor + 30 + name_len;
      std::size_t extra_pos = 0;
      bool found_zip64 = false;
      while (extra_pos + 4 <= static_cast<std::size_t>(extra_len)) {
        const std::uint16_t tag = read_u16_le(extra + extra_pos);
        const std::uint16_t data_size = read_u16_le(extra + extra_pos + 2);
        if (extra_pos + 4 + data_size > static_cast<std::size_t>(extra_len)) {
          break;
        }
        if (tag == 0x0001u) {
          std::size_t inner = 0;
          if (uncompressed_size == 0xFFFFFFFFull && inner + 8 <= data_size) {
            uncompressed_size =
                read_u64_le(extra + extra_pos + 4 + inner);
            inner += 8;
          }
          if (compressed_size == 0xFFFFFFFFull && inner + 8 <= data_size) {
            compressed_size = read_u64_le(extra + extra_pos + 4 + inner);
            inner += 8;
          }
          found_zip64 = true;
          break;
        }
        extra_pos += 4 + data_size;
      }
      if (!found_zip64) {
        fail("npz local file header marked ZIP64 but lacks a 0x0001 extra");
      }
    }
    if (compressed_size != uncompressed_size) {
      fail("npz fixture has compressed entry where stored is required");
    }
    if (cursor + header_size + compressed_size > bytes.size()) {
      fail("npz entry runs past archive end");
    }
    std::string name(reinterpret_cast<const char*>(bytes.data() + cursor + 30),
                     name_len);
    if (name.size() >= 4 &&
        std::string_view{name}.substr(name.size() - 4) ==
            std::string_view{".npy"}) {
      name = name.substr(0, name.size() - 4);
    }
    NpyEntry entry = parse_npy(bytes.data() + cursor + header_size,
                               compressed_size);
    out_entries.emplace_back(std::move(name), std::move(entry));
    cursor += header_size + compressed_size;
  }
  if (out_entries.empty()) {
    fail("npz fixture contained no entries: " + path.string());
  }
}

const NpyEntry* find_entry(
    const std::vector<std::pair<std::string, NpyEntry>>& entries,
    const std::string_view name) noexcept {
  for (const auto& entry : entries) {
    if (entry.first == name) {
      return &entry.second;
    }
  }
  return nullptr;
}

// === Fixture path resolution ==============================================

std::filesystem::path fixture_path() {
  const char* explicit_path = std::getenv("HIKOBOSHI_ESM2_PYTORCH_GOLDENS");
  if (explicit_path != nullptr && *explicit_path != '\0') {
    return std::filesystem::path{explicit_path};
  }
  const char* source_root = std::getenv("HIKOBOSHI_SOURCE_ROOT");
  if (source_root != nullptr && *source_root != '\0') {
    return std::filesystem::path{source_root} / "tests" / "cpp" / "data" /
           "esm2_pytorch_goldens.npz";
  }
  return std::filesystem::path{"tests/cpp/data/esm2_pytorch_goldens.npz"};
}

// === Encoder execution ====================================================

std::vector<std::int32_t> tokens_from_entry(const NpyEntry& entry) {
  if (entry.dtype != "<i4" && entry.dtype != "|i4" && entry.dtype != "i4") {
    fail("input_tokens must be int32 (dtype=<i4), got " + entry.dtype);
  }
  if (entry.shape.size() != 1) {
    fail("input_tokens must be rank-1");
  }
  const std::size_t count = entry.shape[0];
  if (entry.data.size() != count * sizeof(std::int32_t)) {
    fail("input_tokens byte length does not match shape");
  }
  std::vector<std::int32_t> tokens(count);
  std::memcpy(tokens.data(), entry.data.data(), entry.data.size());
  return tokens;
}

std::vector<float> floats_from_entry(const NpyEntry& entry) {
  if (entry.dtype != "<f4" && entry.dtype != "|f4" && entry.dtype != "f4") {
    fail("output_embeddings must be float32 (dtype=<f4), got " + entry.dtype);
  }
  if (entry.shape.size() != 2) {
    fail("output_embeddings must be rank-2");
  }
  const std::size_t count = entry.shape[0] * entry.shape[1];
  if (entry.data.size() != count * sizeof(float)) {
    fail("output_embeddings byte length does not match shape");
  }
  std::vector<float> values(count);
  std::memcpy(values.data(), entry.data.data(), entry.data.size());
  return values;
}

hiko_m::Esm2Descriptor make_descriptor(std::size_t seq_len) noexcept {
  hiko_m::Esm2Descriptor descriptor{};
  descriptor.vocab_size = kEsm2VocabSize;
  descriptor.hidden_dimension = kEsm2HiddenDim;
  descriptor.layer_count = kEsm2LayerCount;
  descriptor.head_count = kEsm2HeadCount;
  descriptor.head_dim = kEsm2HeadDim;
  descriptor.ffn_hidden_dimension = kEsm2FfnHiddenDim;
  descriptor.max_sequence_length = std::max(seq_len, kEsm2MaxSequenceLength);
  return descriptor;
}

void run_hikoboshi_encoder(const std::vector<std::int32_t>& tokens,
                         std::vector<float>& embeddings) {
  const hiko_u::Result<hiko_u::WeightsHandle> handle = hiko_w::default_esm2_8m();
  if (handle.status.code != hiko_u::StatusCode::Ok) {
    fail("default_esm2_8m() must resolve to a valid weights handle");
  }
  if (handle.value.view == nullptr) {
    fail("default_esm2_8m() returned a null weights view");
  }
  const hiko_m::Esm2Descriptor descriptor = make_descriptor(tokens.size());
  embeddings.assign(tokens.size() * descriptor.hidden_dimension, 0.0F);
  const hiko_u::Span<const std::int32_t> token_span{tokens.data(), tokens.size()};
  const hiko_u::Status status = hiko::detail::encode_esm2_sequence(
      *handle.value.view, descriptor, token_span, embeddings.data());
  if (!hiko_u::is_ok(status)) {
    std::string detail = "encode_esm2_sequence failed";
    if (status.detail != nullptr && *status.detail != '\0') {
      detail += std::string(": ") + status.detail;
    }
    fail(detail);
  }
}

// === Comparison + reporting ==============================================

struct DeltaReport {
  float max_abs = 0.0F;
  std::size_t max_abs_index = 0;
  double l2 = 0.0;
  std::size_t worst_row = 0;
  float worst_row_max_abs = 0.0F;
};

DeltaReport compute_delta(const std::vector<float>& hiko_values,
                          const std::vector<float>& golden,
                          std::size_t seq_len, std::size_t hidden) {
  if (hiko_values.size() != golden.size() || hiko_values.size() != seq_len * hidden) {
    fail("delta inputs have inconsistent sizes");
  }
  DeltaReport report{};
  double sum_sq = 0.0;
  for (std::size_t row = 0; row < seq_len; ++row) {
    float row_max = 0.0F;
    for (std::size_t col = 0; col < hidden; ++col) {
      const std::size_t i = row * hidden + col;
      const float diff = std::fabs(hiko_values[i] - golden[i]);
      sum_sq += static_cast<double>(diff) * static_cast<double>(diff);
      if (diff > report.max_abs) {
        report.max_abs = diff;
        report.max_abs_index = i;
      }
      if (diff > row_max) {
        row_max = diff;
      }
    }
    if (row_max > report.worst_row_max_abs) {
      report.worst_row_max_abs = row_max;
      report.worst_row = row;
    }
  }
  report.l2 = std::sqrt(sum_sq);
  return report;
}

}  // namespace

int main() {
  const std::filesystem::path fixture = fixture_path();
  std::vector<std::pair<std::string, NpyEntry>> entries;
  read_npz(fixture, entries);

  const NpyEntry* tokens_entry = find_entry(entries, "input_tokens");
  const NpyEntry* golden_entry = find_entry(entries, "output_embeddings");
  if (tokens_entry == nullptr) {
    fail("npz fixture missing 'input_tokens' entry: " + fixture.string());
  }
  if (golden_entry == nullptr) {
    fail("npz fixture missing 'output_embeddings' entry: " + fixture.string());
  }

  const std::vector<std::int32_t> tokens = tokens_from_entry(*tokens_entry);
  const std::vector<float> golden = floats_from_entry(*golden_entry);
  const std::size_t seq_len = tokens.size();
  if (seq_len == 0) {
    fail("npz fixture token sequence is empty");
  }
  if (golden_entry->shape[0] != seq_len ||
      golden_entry->shape[1] != kEsm2HiddenDim) {
    fail("golden embedding shape does not match (seq_len, 320)");
  }

  std::vector<float> embeddings;
  run_hikoboshi_encoder(tokens, embeddings);

  const DeltaReport delta = compute_delta(embeddings, golden, seq_len,
                                          kEsm2HiddenDim);
  const float tolerance = active_tolerance();
  const char* mode_tag =
      (tolerance <= strict_tolerance()) ? "strict" : "fast";

  // Always print the deltas, including on success, so drift is visible
  // before a future regression actually fails the test.
  std::printf(
      "esm2_pytorch_real_parity: seq_len=%zu hidden=%zu max_abs=%.6e "
      "l2=%.6e worst_row=%zu worst_row_max_abs=%.6e mode=%s tolerance=%.6e\n",
      seq_len, static_cast<std::size_t>(kEsm2HiddenDim),
      static_cast<double>(delta.max_abs), delta.l2, delta.worst_row,
      static_cast<double>(delta.worst_row_max_abs), mode_tag,
      static_cast<double>(tolerance));

  if (!(delta.max_abs <= tolerance)) {
    std::fprintf(
        stderr,
        "esm2_pytorch_real_parity: max abs %.6e at index %zu exceeds "
        "%s tolerance %.6e (worst row=%zu row_max=%.6e, l2=%.6e); the "
        "in-tree naive reference may share the same bug — bisect by "
        "running scripts/esm2_pytorch_goldens.py with per-layer dumps "
        "and comparing against Hikoboshi's compound module intermediates\n",
        static_cast<double>(delta.max_abs), delta.max_abs_index, mode_tag,
        static_cast<double>(tolerance), delta.worst_row,
        static_cast<double>(delta.worst_row_max_abs), delta.l2);
    return 1;
  }
  return 0;
}
