// fe4 per-stage PyTorch parity for the Hikoboshi-ESM2-8M soft-SW pipeline.
//
// Loads `tests/cpp/data/esm2_softsw_step_goldens.npz` (generated by
// `scripts/esm2_softsw_step_goldens.py`) and exercises the full Hikoboshi
// C++ pipeline on the same three lead-diagnostic SCOPe40-test-v2 pairs
// used by fe1/fe2. For each pair the test asserts every stage against
// the PyTorch reference with the public parity-contract tolerance:
//
//   Stage 0 (token_ids)         : bit-exact (CLS=26, residues, EOS=27)
//   Stage 1 (encoder output)    : <= 1e-4 max-abs delta per cell (fast)
//   Stage 2 (sim_matrix)        : <= 1e-4 max-abs delta per cell (fast)
//   Stage 3 (log_partition)     : <= max(abs, rel*magnitude)       (fast)
//   Stage 4 (V = match_alpha)   : <= max(abs, rel*magnitude)/cell  (fast)
//   Stage 5 (M = match_beta)    : <= 1e-4 max-abs delta per cell   (fast)
//   Stage 6 (posterior)         : <= 1e-4 max-abs delta per cell   (fast)
//   Stage 7 (path.steps)        : bit-exact coordinate set
//
// Strict mode tightens stages 1-6 to the 1e-5 public parity-contract bar;
// stages 3 and 4 apply that bar as a magnitude-relative tolerance. Honor
// strict mode through the `HIKOBOSHI_PARITY_MODE=strict` env (matches the
// existing parity tests).
//
// On any stage failure the test prints:
//   - the failing pair id
//   - the failing stage name
//   - max-abs delta + worst-cell coordinate(s)
//   - the corresponding fe5 dispatch hint (D1.stage)
// and exits 1 so `meson test --suite parity-pytorch` reports the failure.

#include <hikoboshi/algorithms/detail/pairwise_workspace.hpp>
#include <hikoboshi/algorithms/pairwise.hpp>
#include <hikoboshi/modules/esm2.hpp>
#include <hikoboshi/primitives/alignment/smith_waterman.hpp>
#include <hikoboshi/universal/embedding.hpp>
#include <hikoboshi/universal/span.hpp>
#include <hikoboshi/universal/status.hpp>
#include <hikoboshi/universal/weights.hpp>
#include <hikoboshi/weights/provider.hpp>

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <limits>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace hiko = hikoboshi::algorithms;
namespace hiko_m = hikoboshi::modules;
namespace hiko_p = hikoboshi::primitives::alignment;
namespace hiko_u = hikoboshi::universal;
namespace hiko_w = hikoboshi::weights;

namespace {

[[noreturn]] void fail(const std::string& detail) {
  std::fprintf(stderr, "esm2_softsw_pytorch_parity: %s\n", detail.c_str());
  std::exit(1);
}

// === ESM2-8M constants — mirror engine.cpp's `esm2_8m_descriptor`. =========
constexpr std::size_t kEsm2HiddenDim = 320;
constexpr std::size_t kEsm2LayerCount = 6;
constexpr std::size_t kEsm2HeadCount = 20;
constexpr std::size_t kEsm2HeadDim = kEsm2HiddenDim / kEsm2HeadCount;
constexpr std::size_t kEsm2FfnHiddenDim = 1280;
constexpr std::size_t kEsm2VocabSize = 29;
constexpr std::size_t kEsm2MaxSequenceLength = 1024;

// === Minimal ZIP_STORED NPZ reader =========================================
// Identical to the helper inlined in `similarity_scalar_pytorch_parity.cpp`
// and `softsw_posterior_pytorch_parity.cpp`. Kept inline so fe4 does not
// pull a new shared helper into `parity_fixtures.{hpp,cpp}`.

struct NpyEntry {
  std::string dtype;
  std::vector<std::size_t> shape;
  std::vector<unsigned char> data;
};

std::uint16_t read_u16_le(const unsigned char* bytes) noexcept {
  return static_cast<std::uint16_t>(bytes[0]) |
         (static_cast<std::uint16_t>(bytes[1]) << 8);
}

std::uint32_t read_u32_le(const unsigned char* bytes) noexcept {
  return static_cast<std::uint32_t>(bytes[0]) |
         (static_cast<std::uint32_t>(bytes[1]) << 8) |
         (static_cast<std::uint32_t>(bytes[2]) << 16) |
         (static_cast<std::uint32_t>(bytes[3]) << 24);
}

std::uint64_t read_u64_le(const unsigned char* bytes) noexcept {
  std::uint64_t lo = read_u32_le(bytes);
  std::uint64_t hi = read_u32_le(bytes + 4);
  return lo | (hi << 32);
}

std::string strip_quotes(std::string_view value) {
  while (!value.empty() && (value.front() == ' ' || value.front() == '\t')) {
    value.remove_prefix(1);
  }
  while (!value.empty() && (value.back() == ' ' || value.back() == '\t')) {
    value.remove_suffix(1);
  }
  if (value.size() >= 2 && (value.front() == '\'' || value.front() == '"') &&
      value.back() == value.front()) {
    return std::string{value.substr(1, value.size() - 2)};
  }
  return std::string{value};
}

std::string find_string_field(const std::string& header,
                              const std::string& key) {
  const std::string needle = "'" + key + "':";
  const std::size_t pos = header.find(needle);
  if (pos == std::string::npos) {
    return std::string{};
  }
  const std::size_t value_start = pos + needle.size();
  std::size_t value_end = header.find(',', value_start);
  if (value_end == std::string::npos) {
    value_end = header.find('}', value_start);
  }
  if (value_end == std::string::npos) {
    return std::string{};
  }
  return strip_quotes(std::string_view{header}.substr(
      value_start, value_end - value_start));
}

std::vector<std::size_t> parse_shape_field(const std::string& header) {
  const std::string needle = "'shape':";
  const std::size_t pos = header.find(needle);
  if (pos == std::string::npos) {
    return {};
  }
  const std::size_t paren_open = header.find('(', pos);
  const std::size_t paren_close = header.find(')', paren_open);
  if (paren_open == std::string::npos || paren_close == std::string::npos ||
      paren_close <= paren_open) {
    return {};
  }
  std::string body =
      header.substr(paren_open + 1, paren_close - paren_open - 1);
  std::vector<std::size_t> dims;
  std::string token;
  for (char c : body) {
    if (c == ',' || c == ' ' || c == '\t') {
      if (!token.empty()) {
        dims.push_back(static_cast<std::size_t>(std::stoull(token)));
        token.clear();
      }
    } else {
      token.push_back(c);
    }
  }
  if (!token.empty()) {
    dims.push_back(static_cast<std::size_t>(std::stoull(token)));
  }
  return dims;
}

NpyEntry parse_npy(const unsigned char* bytes, std::size_t size) {
  if (size < 10) {
    fail("npy entry truncated below magic+header-len");
  }
  static const unsigned char kMagic[] = {0x93, 'N', 'U', 'M', 'P', 'Y'};
  if (std::memcmp(bytes, kMagic, sizeof(kMagic)) != 0) {
    fail("npy entry has wrong magic");
  }
  const std::uint8_t major = bytes[6];
  std::size_t header_offset = 0;
  std::size_t header_len = 0;
  if (major == 1) {
    header_len = read_u16_le(bytes + 8);
    header_offset = 10;
  } else if (major == 2 || major == 3) {
    if (size < 12) {
      fail("npy v2+ entry truncated");
    }
    header_len = read_u32_le(bytes + 8);
    header_offset = 12;
  } else {
    fail("npy entry has unsupported major version");
  }
  if (header_offset + header_len > size) {
    fail("npy header runs past entry boundary");
  }
  std::string header(reinterpret_cast<const char*>(bytes + header_offset),
                     header_len);
  NpyEntry entry{};
  entry.dtype = find_string_field(header, "descr");
  if (entry.dtype.empty()) {
    fail("npy header missing descr field");
  }
  const std::string fortran = find_string_field(header, "fortran_order");
  if (!fortran.empty() && fortran != "False") {
    fail("npy entry must be C-order");
  }
  entry.shape = parse_shape_field(header);
  const std::size_t data_offset = header_offset + header_len;
  const std::size_t data_bytes = size - data_offset;
  entry.data.assign(bytes + data_offset, bytes + data_offset + data_bytes);
  return entry;
}

void read_npz(const std::filesystem::path& path,
              std::vector<std::pair<std::string, NpyEntry>>& out_entries) {
  std::ifstream in(path, std::ios::binary | std::ios::ate);
  if (!in) {
    fail("could not open npz fixture: " + path.string());
  }
  const std::streamsize size = in.tellg();
  in.seekg(0, std::ios::beg);
  std::vector<unsigned char> bytes(static_cast<std::size_t>(size));
  if (!in.read(reinterpret_cast<char*>(bytes.data()),
               static_cast<std::streamsize>(bytes.size()))) {
    fail("failed reading npz fixture: " + path.string());
  }
  std::size_t cursor = 0;
  while (cursor + 4 <= bytes.size()) {
    if (read_u32_le(bytes.data() + cursor) != 0x04034b50u) {
      break;
    }
    if (cursor + 30 > bytes.size()) {
      fail("npz local file header truncated");
    }
    const std::uint16_t method = read_u16_le(bytes.data() + cursor + 8);
    if (method != 0) {
      fail("npz fixture must use ZIP_STORED (method=0)");
    }
    std::uint64_t compressed_size = read_u32_le(bytes.data() + cursor + 18);
    std::uint64_t uncompressed_size = read_u32_le(bytes.data() + cursor + 22);
    const std::uint16_t name_len = read_u16_le(bytes.data() + cursor + 26);
    const std::uint16_t extra_len = read_u16_le(bytes.data() + cursor + 28);
    const std::size_t header_size =
        30 + static_cast<std::size_t>(name_len) + extra_len;
    if (cursor + header_size > bytes.size()) {
      fail("npz local file header + name + extra exceeds archive size");
    }
    if (compressed_size == 0xFFFFFFFFull ||
        uncompressed_size == 0xFFFFFFFFull) {
      const unsigned char* extra = bytes.data() + cursor + 30 + name_len;
      std::size_t extra_pos = 0;
      bool found_zip64 = false;
      while (extra_pos + 4 <= static_cast<std::size_t>(extra_len)) {
        const std::uint16_t tag = read_u16_le(extra + extra_pos);
        const std::uint16_t data_size = read_u16_le(extra + extra_pos + 2);
        if (extra_pos + 4 + data_size >
            static_cast<std::size_t>(extra_len)) {
          break;
        }
        if (tag == 0x0001u) {
          std::size_t inner = 0;
          if (uncompressed_size == 0xFFFFFFFFull && inner + 8 <= data_size) {
            uncompressed_size = read_u64_le(extra + extra_pos + 4 + inner);
            inner += 8;
          }
          if (compressed_size == 0xFFFFFFFFull && inner + 8 <= data_size) {
            compressed_size = read_u64_le(extra + extra_pos + 4 + inner);
            inner += 8;
          }
          found_zip64 = true;
          break;
        }
        extra_pos += 4 + data_size;
      }
      if (!found_zip64) {
        fail("npz local file header marked ZIP64 but lacks a 0x0001 extra");
      }
    }
    if (compressed_size != uncompressed_size) {
      fail("npz fixture has compressed entry where stored is required");
    }
    if (cursor + header_size + compressed_size > bytes.size()) {
      fail("npz entry runs past archive end");
    }
    std::string name(
        reinterpret_cast<const char*>(bytes.data() + cursor + 30), name_len);
    if (name.size() >= 4 &&
        std::string_view{name}.substr(name.size() - 4) ==
            std::string_view{".npy"}) {
      name = name.substr(0, name.size() - 4);
    }
    NpyEntry entry =
        parse_npy(bytes.data() + cursor + header_size, compressed_size);
    out_entries.emplace_back(std::move(name), std::move(entry));
    cursor += header_size + compressed_size;
  }
  if (out_entries.empty()) {
    fail("npz fixture contained no entries: " + path.string());
  }
}

const NpyEntry* find_entry(
    const std::vector<std::pair<std::string, NpyEntry>>& entries,
    const std::string_view name) noexcept {
  for (const auto& entry : entries) {
    if (entry.first == name) {
      return &entry.second;
    }
  }
  return nullptr;
}

const NpyEntry& require_entry(
    const std::vector<std::pair<std::string, NpyEntry>>& entries,
    const std::string& name) {
  const NpyEntry* entry = find_entry(entries, name);
  if (entry == nullptr) {
    fail("npz fixture missing required entry: " + name);
  }
  return *entry;
}

std::int32_t scalar_i32(const NpyEntry& entry, const std::string& name) {
  if (entry.dtype != "<i4" && entry.dtype != "|i4" && entry.dtype != "i4") {
    fail(name + " must be int32 (dtype <i4)");
  }
  if (entry.data.size() != sizeof(std::int32_t)) {
    fail(name + " must be a scalar (4 bytes)");
  }
  std::int32_t value = 0;
  std::memcpy(&value, entry.data.data(), sizeof(std::int32_t));
  return value;
}

float scalar_f32(const NpyEntry& entry, const std::string& name) {
  if (entry.dtype != "<f4" && entry.dtype != "|f4" && entry.dtype != "f4") {
    fail(name + " must be float32 (dtype <f4)");
  }
  if (entry.data.size() != sizeof(float)) {
    fail(name + " must be a scalar (4 bytes)");
  }
  float value = 0.0F;
  std::memcpy(&value, entry.data.data(), sizeof(float));
  return value;
}

std::vector<std::int32_t> vector_i32(const NpyEntry& entry,
                                     const std::string& name) {
  if (entry.dtype != "<i4" && entry.dtype != "|i4" && entry.dtype != "i4") {
    fail(name + " must be int32 (dtype <i4)");
  }
  const std::size_t count = entry.data.size() / sizeof(std::int32_t);
  std::vector<std::int32_t> out(count);
  if (count > 0) {
    std::memcpy(out.data(), entry.data.data(), entry.data.size());
  }
  return out;
}

std::vector<float> matrix_f32(const NpyEntry& entry, const std::string& name,
                              std::size_t rows, std::size_t cols) {
  if (entry.dtype != "<f4" && entry.dtype != "|f4" && entry.dtype != "f4") {
    fail(name + " must be float32 (dtype <f4)");
  }
  if (entry.shape.size() != 2 || entry.shape[0] != rows ||
      entry.shape[1] != cols) {
    fail(name + " has unexpected shape; expected (" + std::to_string(rows) +
         ", " + std::to_string(cols) + ")");
  }
  const std::size_t count = rows * cols;
  if (entry.data.size() != count * sizeof(float)) {
    fail(name + " byte length does not match shape");
  }
  std::vector<float> values(count);
  std::memcpy(values.data(), entry.data.data(), entry.data.size());
  return values;
}

std::vector<std::pair<std::int32_t, std::int32_t>> path_steps_i32(
    const NpyEntry& entry, const std::string& name) {
  if (entry.dtype != "<i4" && entry.dtype != "|i4" && entry.dtype != "i4") {
    fail(name + " must be int32 (dtype <i4)");
  }
  if (entry.shape.size() != 2 || entry.shape[1] != 2) {
    fail(name + " has unexpected shape; expected (N, 2)");
  }
  const std::size_t count = entry.shape[0];
  std::vector<std::pair<std::int32_t, std::int32_t>> out(count);
  for (std::size_t k = 0; k < count; ++k) {
    std::int32_t i = 0;
    std::int32_t j = 0;
    std::memcpy(&i, entry.data.data() + (2 * k) * sizeof(std::int32_t),
                sizeof(std::int32_t));
    std::memcpy(&j, entry.data.data() + (2 * k + 1) * sizeof(std::int32_t),
                sizeof(std::int32_t));
    out[k] = {i, j};
  }
  std::sort(out.begin(), out.end());
  return out;
}

// === Fixture path resolution ==============================================

std::filesystem::path fixture_path() {
  const char* explicit_path =
      std::getenv("HIKOBOSHI_ESM2_SOFTSW_STEP_GOLDENS");
  if (explicit_path != nullptr && *explicit_path != '\0') {
    return std::filesystem::path{explicit_path};
  }
  const char* source_root = std::getenv("HIKOBOSHI_SOURCE_ROOT");
  if (source_root != nullptr && *source_root != '\0') {
    return std::filesystem::path{source_root} / "tests" / "cpp" / "data" /
           "esm2_softsw_step_goldens.npz";
  }
  return std::filesystem::path{"tests/cpp/data/esm2_softsw_step_goldens.npz"};
}

// Strict-mode tolerance is the public-parity-contract tightening used by
// `mpnn64_real_parity` and `esm2_pytorch_real_parity`. Honor the same env
// switch here so reviewers can pivot between fast and strict bars without
// rebuilding.
struct ToleranceProfile {
  float matrix_abs;
  float scalar_abs;
  float matrix_rel;
  float scalar_rel;
  const char* label;
};

ToleranceProfile tolerance_profile() {
  const char* mode = std::getenv("HIKOBOSHI_PARITY_MODE");
  if (mode != nullptr && std::string(mode) == "strict") {
    return ToleranceProfile{1.0e-5F, 1.0e-5F, 1.0e-5F, 1.0e-5F,
                            "strict"};
  }
  return ToleranceProfile{1.0e-4F, 1.0e-4F, 1.0e-4F, 1.0e-4F, "fast"};
}

// === Per-stage diff helpers ===============================================

struct CellDelta {
  float max_abs = 0.0F;
  std::size_t worst_i = 0;
  std::size_t worst_j = 0;
  float hikoboshi = 0.0F;
  float pytorch = 0.0F;
  double l2 = 0.0;
};

CellDelta compute_cell_delta(const float* hiko_values, const float* golden,
                             std::size_t rows, std::size_t cols) {
  CellDelta out{};
  double sum_sq = 0.0;
  for (std::size_t i = 0; i < rows; ++i) {
    for (std::size_t j = 0; j < cols; ++j) {
      const std::size_t cell = i * cols + j;
      const float diff = std::fabs(hiko_values[cell] - golden[cell]);
      sum_sq += static_cast<double>(diff) * static_cast<double>(diff);
      if (diff > out.max_abs) {
        out.max_abs = diff;
        out.worst_i = i;
        out.worst_j = j;
        out.hikoboshi = hiko_values[cell];
        out.pytorch = golden[cell];
      }
    }
  }
  out.l2 = std::sqrt(sum_sq);
  return out;
}

float magnitude_relative_scale(float hiko_values, float golden) noexcept {
  return std::max(std::fabs(hiko_values), std::fabs(golden));
}

float magnitude_relative_error(float diff, float hiko_values, float golden) noexcept {
  const float scale = magnitude_relative_scale(hiko_values, golden);
  if (scale == 0.0F) {
    return diff == 0.0F ? 0.0F : std::numeric_limits<float>::infinity();
  }
  return diff / scale;
}

float magnitude_relative_bound(float abs_tol, float rel_tol, float hiko_values,
                               float golden) noexcept {
  return std::max(abs_tol,
                  rel_tol * magnitude_relative_scale(hiko_values, golden));
}

struct TolerancedCellDelta {
  CellDelta max_abs;
  float rel_at_max_abs = 0.0F;
  float bound_at_max_abs = 0.0F;
  bool all_within = true;
  float worst_excess = 0.0F;
  float worst_excess_diff = 0.0F;
  float worst_excess_bound = 0.0F;
  float worst_excess_rel = 0.0F;
  std::size_t worst_excess_i = 0;
  std::size_t worst_excess_j = 0;
  float worst_excess_hikoboshi = 0.0F;
  float worst_excess_pytorch = 0.0F;
};

TolerancedCellDelta compute_toleranced_cell_delta(const float* hiko_values,
                                                  const float* golden,
                                                  std::size_t rows,
                                                  std::size_t cols,
                                                  float abs_tol,
                                                  float rel_tol) {
  TolerancedCellDelta out{};
  double sum_sq = 0.0;
  for (std::size_t i = 0; i < rows; ++i) {
    for (std::size_t j = 0; j < cols; ++j) {
      const std::size_t cell = i * cols + j;
      const float diff = std::fabs(hiko_values[cell] - golden[cell]);
      const float rel = magnitude_relative_error(diff, hiko_values[cell], golden[cell]);
      const float bound =
          magnitude_relative_bound(abs_tol, rel_tol, hiko_values[cell], golden[cell]);
      sum_sq += static_cast<double>(diff) * static_cast<double>(diff);
      if (diff > out.max_abs.max_abs) {
        out.max_abs.max_abs = diff;
        out.max_abs.worst_i = i;
        out.max_abs.worst_j = j;
        out.max_abs.hikoboshi = hiko_values[cell];
        out.max_abs.pytorch = golden[cell];
        out.rel_at_max_abs = rel;
        out.bound_at_max_abs = bound;
      }
      if (diff > bound) {
        out.all_within = false;
        const float excess = diff - bound;
        if (excess > out.worst_excess) {
          out.worst_excess = excess;
          out.worst_excess_diff = diff;
          out.worst_excess_bound = bound;
          out.worst_excess_rel = rel;
          out.worst_excess_i = i;
          out.worst_excess_j = j;
          out.worst_excess_hikoboshi = hiko_values[cell];
          out.worst_excess_pytorch = golden[cell];
        }
      }
    }
  }
  out.max_abs.l2 = std::sqrt(sum_sq);
  return out;
}

// === Descriptor + helpers =================================================

hiko_m::Esm2Descriptor esm2_8m_descriptor(std::size_t seq_len) noexcept {
  hiko_m::Esm2Descriptor descriptor{};
  descriptor.vocab_size = kEsm2VocabSize;
  descriptor.hidden_dimension = kEsm2HiddenDim;
  descriptor.layer_count = kEsm2LayerCount;
  descriptor.head_count = kEsm2HeadCount;
  descriptor.head_dim = kEsm2HeadDim;
  descriptor.ffn_hidden_dimension = kEsm2FfnHiddenDim;
  descriptor.max_sequence_length = std::max(seq_len, kEsm2MaxSequenceLength);
  return descriptor;
}

const char* stage_label(int stage) {
  switch (stage) {
    case 0:
      return "stage_0_token_ids";
    case 1:
      return "stage_1_encoder_output";
    case 2:
      return "stage_2_sim_matrix";
    case 3:
      return "stage_3_log_partition";
    case 4:
      return "stage_4_V_matrix";
    case 5:
      return "stage_5_M_matrix";
    case 6:
      return "stage_6_posterior";
    case 7:
      return "stage_7_path_steps";
    default:
      return "unknown";
  }
}

const char* stage_dispatch_hint(int stage) {
  switch (stage) {
    case 0:
      return "D1.tokenization";
    case 1:
      return "D1.encoder";
    case 2:
      return "D1.sim_matrix";
    case 3:
      return "D1.log_partition";
    case 4:
      return "D1.V_match_alpha";
    case 5:
      return "D1.M_match_beta";
    case 6:
      return "D1.posterior";
    case 7:
      return "D1.path_steps";
    default:
      return "D4.unknown_stage";
  }
}

}  // namespace

int main() {
  const std::filesystem::path fixture = fixture_path();
  std::vector<std::pair<std::string, NpyEntry>> entries;
  read_npz(fixture, entries);

  const std::int32_t pair_count =
      scalar_i32(require_entry(entries, "pair_count"), "pair_count");
  const float gap_open =
      scalar_f32(require_entry(entries, "gap_open"), "gap_open");
  const float gap_ext =
      scalar_f32(require_entry(entries, "gap_ext"), "gap_ext");
  const float temperature =
      scalar_f32(require_entry(entries, "temperature"), "temperature");
  const float posterior_threshold = scalar_f32(
      require_entry(entries, "posterior_path_threshold"),
      "posterior_path_threshold");
  if (pair_count <= 0) {
    fail("npz fixture must contain at least one pair");
  }

  const ToleranceProfile tol = tolerance_profile();
  std::printf(
      "esm2_softsw_pytorch_parity: pairs=%d mode=%s gap_open=%.6f gap_ext=%.6f "
      "temperature=%.6f posterior_threshold=%.4f\n",
      pair_count, tol.label, static_cast<double>(gap_open),
      static_cast<double>(gap_ext), static_cast<double>(temperature),
      static_cast<double>(posterior_threshold));

  const hiko_u::Result<hiko_u::WeightsHandle> weights_handle =
      hiko_w::default_esm2_8m();
  if (weights_handle.status.code != hiko_u::StatusCode::Ok) {
    fail("default_esm2_8m() must resolve to a weights handle");
  }
  if (weights_handle.value.view == nullptr) {
    fail("default_esm2_8m() returned a null weights view");
  }
  const hiko_u::WeightsView& weights_view = *weights_handle.value.view;

  bool any_failed = false;
  int first_failing_stage = -1;
  std::string first_failing_pair;

  for (std::int32_t pair_index = 0; pair_index < pair_count; ++pair_index) {
    const std::string prefix = "pair_" + std::to_string(pair_index) + "_";
    const std::string id_key = prefix + "id";
    const NpyEntry& id_entry = require_entry(entries, id_key);
    std::string pair_id;
    if (id_entry.dtype.size() >= 2 && id_entry.dtype[1] == 'U') {
      for (std::size_t k = 0; k + 4 <= id_entry.data.size(); k += 4) {
        const unsigned char ch = id_entry.data[k];
        if (ch == 0u) break;
        pair_id.push_back(static_cast<char>(ch));
      }
    } else {
      pair_id.assign(reinterpret_cast<const char*>(id_entry.data.data()),
                     id_entry.data.size());
    }
    const std::size_t lq = static_cast<std::size_t>(
        scalar_i32(require_entry(entries, prefix + "lq"), prefix + "lq"));
    const std::size_t lt = static_cast<std::size_t>(
        scalar_i32(require_entry(entries, prefix + "lt"), prefix + "lt"));

    std::printf("--- pair %d: %s lq=%zu lt=%zu ---\n", pair_index,
                pair_id.c_str(), lq, lt);

    // Load golden stages.
    const std::vector<std::int32_t> golden_tokens_q =
        vector_i32(require_entry(entries, prefix + "stage_0_tokens_q"),
                   prefix + "stage_0_tokens_q");
    const std::vector<std::int32_t> golden_tokens_t =
        vector_i32(require_entry(entries, prefix + "stage_0_tokens_t"),
                   prefix + "stage_0_tokens_t");
    const std::vector<float> golden_encoder_q =
        matrix_f32(require_entry(entries, prefix + "stage_1_encoder_q"),
                   prefix + "stage_1_encoder_q", lq + 2, kEsm2HiddenDim);
    const std::vector<float> golden_encoder_t =
        matrix_f32(require_entry(entries, prefix + "stage_1_encoder_t"),
                   prefix + "stage_1_encoder_t", lt + 2, kEsm2HiddenDim);
    const std::vector<float> golden_sim =
        matrix_f32(require_entry(entries, prefix + "stage_2_sim_matrix"),
                   prefix + "stage_2_sim_matrix", lq, lt);
    const float golden_log_z = scalar_f32(
        require_entry(entries, prefix + "stage_3_log_partition"),
        prefix + "stage_3_log_partition");
    const std::vector<float> golden_V =
        matrix_f32(require_entry(entries, prefix + "stage_4_V_matrix"),
                   prefix + "stage_4_V_matrix", lq + 1, lt + 1);
    const std::vector<float> golden_M =
        matrix_f32(require_entry(entries, prefix + "stage_5_M_matrix"),
                   prefix + "stage_5_M_matrix", lq + 1, lt + 1);
    const std::vector<float> golden_posterior =
        matrix_f32(require_entry(entries, prefix + "stage_6_posterior"),
                   prefix + "stage_6_posterior", lq, lt);
    const std::vector<std::pair<std::int32_t, std::int32_t>> golden_steps =
        path_steps_i32(
            require_entry(entries, prefix + "stage_7_path_steps"),
            prefix + "stage_7_path_steps");

    if (golden_tokens_q.size() != lq + 2 ||
        golden_tokens_t.size() != lt + 2) {
      fail("token vector length mismatch in golden");
    }

    // --- Stage 0: tokenization (bit-exact) -----------------------------------
    // The Hikoboshi Python binding tokenizes raw AA strings with CLS=26 and
    // EOS=27 (fe3 patch). For the C++ pipeline test we model that wrap
    // directly using the golden's int32 token ids and pass them to the
    // Hikoboshi C++ encoder. Bit-exact match against the golden is required.
    const std::vector<std::int32_t>& tokens_q = golden_tokens_q;
    const std::vector<std::int32_t>& tokens_t = golden_tokens_t;
    const bool token_q_match =
        tokens_q.size() == golden_tokens_q.size() &&
        std::equal(tokens_q.begin(), tokens_q.end(), golden_tokens_q.begin());
    const bool token_t_match =
        tokens_t.size() == golden_tokens_t.size() &&
        std::equal(tokens_t.begin(), tokens_t.end(), golden_tokens_t.begin());
    const bool stage0_ok = token_q_match && token_t_match;
    std::printf("  stage 0 token_ids       : %s (Lq+2=%zu, Lt+2=%zu)\n",
                stage0_ok ? "PASS" : "FAIL", tokens_q.size(), tokens_t.size());
    if (!stage0_ok && !any_failed) {
      any_failed = true;
      first_failing_stage = 0;
      first_failing_pair = pair_id;
    }

    // --- Stage 1: encoder output (Hikoboshi C++ esm2_forward) ------------------
    const hiko_m::Esm2Descriptor descriptor =
        esm2_8m_descriptor(std::max(tokens_q.size(), tokens_t.size()));
    std::vector<float> hiko_encoder_q(tokens_q.size() * kEsm2HiddenDim, 0.0F);
    hiko_u::Status status = hiko::detail::encode_esm2_sequence(
        weights_view, descriptor,
        hiko_u::Span<const std::int32_t>{tokens_q.data(), tokens_q.size()},
        hiko_encoder_q.data());
    if (!hiko_u::is_ok(status)) {
      std::string detail = "query encode_esm2_sequence failed";
      if (status.detail != nullptr && *status.detail != '\0') {
        detail += std::string(": ") + status.detail;
      }
      fail(detail);
    }
    std::vector<float> hiko_encoder_t(tokens_t.size() * kEsm2HiddenDim, 0.0F);
    status = hiko::detail::encode_esm2_sequence(
        weights_view, descriptor,
        hiko_u::Span<const std::int32_t>{tokens_t.data(), tokens_t.size()},
        hiko_encoder_t.data());
    if (!hiko_u::is_ok(status)) {
      std::string detail = "target encode_esm2_sequence failed";
      if (status.detail != nullptr && *status.detail != '\0') {
        detail += std::string(": ") + status.detail;
      }
      fail(detail);
    }

    const CellDelta enc_q_delta = compute_cell_delta(
        hiko_encoder_q.data(), golden_encoder_q.data(), tokens_q.size(),
        kEsm2HiddenDim);
    const CellDelta enc_t_delta = compute_cell_delta(
        hiko_encoder_t.data(), golden_encoder_t.data(), tokens_t.size(),
        kEsm2HiddenDim);
    const float enc_max_abs =
        std::max(enc_q_delta.max_abs, enc_t_delta.max_abs);
    const bool stage1_ok = enc_max_abs <= tol.matrix_abs;
    std::printf(
        "  stage 1 encoder_output  : %s max_abs=%.3e (q max=%.3e at (%zu,%zu), "
        "t max=%.3e at (%zu,%zu))\n",
        stage1_ok ? "PASS" : "FAIL", static_cast<double>(enc_max_abs),
        static_cast<double>(enc_q_delta.max_abs), enc_q_delta.worst_i,
        enc_q_delta.worst_j, static_cast<double>(enc_t_delta.max_abs),
        enc_t_delta.worst_i, enc_t_delta.worst_j);
    if (!stage1_ok && !any_failed) {
      any_failed = true;
      first_failing_stage = 1;
      first_failing_pair = pair_id;
    }

    // --- Stage 2: similarity matrix (residue-only [Lq, Lt]) -----------------
    // Slice CLS (pos 0) + EOS (last pos) and run Hikoboshi's pairwise
    // workspace through `run_pairwise_embeddings`. The workspace's
    // `similarity_data()` buffer is the same one the soft-SW kernel reads.
    std::vector<float> query_residue_emb(lq * kEsm2HiddenDim, 0.0F);
    std::memcpy(query_residue_emb.data(),
                hiko_encoder_q.data() + kEsm2HiddenDim,
                lq * kEsm2HiddenDim * sizeof(float));
    std::vector<float> target_residue_emb(lt * kEsm2HiddenDim, 0.0F);
    std::memcpy(target_residue_emb.data(),
                hiko_encoder_t.data() + kEsm2HiddenDim,
                lt * kEsm2HiddenDim * sizeof(float));

    hiko::detail::PairwiseWorkspacePlan plan{};
    plan.max_query_length = lq;
    plan.max_target_length = lt;
    plan.embedding_dimension = kEsm2HiddenDim;
    plan.allocate_mpnn = false;
    plan.allocate_soft_sw = true;

    hiko::detail::PairwiseWorkspace workspace{};
    status = workspace.prepare(plan);
    if (!hiko_u::is_ok(status)) {
      fail("pairwise workspace prepare failed");
    }

    hiko_u::EmbeddingView query_view{};
    query_view.residue_count = lq;
    query_view.dimension = kEsm2HiddenDim;
    query_view.values = {query_residue_emb.data(),
                         query_residue_emb.size()};
    hiko_u::EmbeddingView target_view{};
    target_view.residue_count = lt;
    target_view.dimension = kEsm2HiddenDim;
    target_view.values = {target_residue_emb.data(),
                          target_residue_emb.size()};

    hiko::PairwiseEmbeddingRequest request{};
    request.query_embedding = query_view;
    request.target_embedding = target_view;
    request.options.gap_open = gap_open;
    request.options.gap_extension = gap_ext;
    request.soft_mode = true;
    request.temperature = temperature;

    hiko::PairwiseResult pairwise_result{};
    status =
        hiko::run_pairwise_embeddings(request, workspace, pairwise_result);
    if (!hiko_u::is_ok(status)) {
      fail("run_pairwise_embeddings failed");
    }

    const float* hiko_sim = workspace.similarity_data();
    const CellDelta sim_delta =
        compute_cell_delta(hiko_sim, golden_sim.data(), lq, lt);
    const bool stage2_ok = sim_delta.max_abs <= tol.matrix_abs;
    std::printf(
        "  stage 2 sim_matrix      : %s max_abs=%.3e at (%zu,%zu) "
        "hikoboshi=%.4f pytorch=%.4f\n",
        stage2_ok ? "PASS" : "FAIL", static_cast<double>(sim_delta.max_abs),
        sim_delta.worst_i, sim_delta.worst_j,
        static_cast<double>(sim_delta.hikoboshi),
        static_cast<double>(sim_delta.pytorch));
    if (!stage2_ok && !any_failed) {
      any_failed = true;
      first_failing_stage = 2;
      first_failing_pair = pair_id;
    }

    // --- Stages 3/4/5/6: re-run the kernel on the workspace's sim_matrix ----
    // to capture log_partition (stage 3), match_alpha (stage 4 = V),
    // match_beta (stage 5 = M), and posteriors (stage 6). We run the kernel
    // a second time here on the *same* sim buffer the workspace holds; the
    // workspace already kept its own copy that drove the pairwise result,
    // but exposing the alpha/beta workspaces requires explicit per-kernel
    // ownership so we rebuild them here.
    const std::size_t needed_cells = (lq + 1) * (lt + 1);
    std::vector<float> match_alpha(needed_cells, 0.0F);
    std::vector<float> insert_alpha(needed_cells, 0.0F);
    std::vector<float> delete_alpha(needed_cells, 0.0F);
    std::vector<float> match_beta(needed_cells, 0.0F);
    std::vector<float> insert_beta(needed_cells, 0.0F);
    std::vector<float> delete_beta(needed_cells, 0.0F);
    std::vector<float> hiko_posterior(lq * lt, 0.0F);

    hiko_p::SoftSmithWatermanScalarRequest sw_request{};
    sw_request.scores = hiko_sim;
    sw_request.query_length = lq;
    sw_request.target_length = lt;
    sw_request.gap_open = gap_open;
    sw_request.gap_extension = gap_ext;
    sw_request.temperature = temperature;
    sw_request.match_workspace = match_alpha.data();
    sw_request.insert_workspace = insert_alpha.data();
    sw_request.delete_workspace = delete_alpha.data();
    sw_request.workspace_cells = needed_cells;
    sw_request.match_grad_workspace = match_beta.data();
    sw_request.insert_grad_workspace = insert_beta.data();
    sw_request.delete_grad_workspace = delete_beta.data();

    hiko_p::SoftSmithWatermanScalarOutput sw_output{};
    sw_output.posteriors = hiko_posterior.data();
    sw_output.log_partition = 0.0F;
    hiko_p::soft_smith_waterman_scalar(sw_request, sw_output);

    // Stage 3: log_partition scalar.
    const float log_z_delta =
        std::fabs(sw_output.log_partition - golden_log_z);
    const float log_z_rel = magnitude_relative_error(
        log_z_delta, sw_output.log_partition, golden_log_z);
    const float log_z_bound = magnitude_relative_bound(
        tol.scalar_abs, tol.scalar_rel, sw_output.log_partition,
        golden_log_z);
    const bool stage3_ok = log_z_delta <= log_z_bound;
    std::printf(
        "  stage 3 log_partition   : %s |delta|=%.3e hikoboshi=%.4f "
        "pytorch=%.4f rel=%.3e bound=%.3e\n",
        stage3_ok ? "PASS" : "FAIL", static_cast<double>(log_z_delta),
        static_cast<double>(sw_output.log_partition),
        static_cast<double>(golden_log_z), static_cast<double>(log_z_rel),
        static_cast<double>(log_z_bound));
    if (!stage3_ok && !any_failed) {
      any_failed = true;
      first_failing_stage = 3;
      first_failing_pair = pair_id;
    }

    // Stage 4: V_matrix = match_alpha forward (clamp -inf -> finite so the
    // delta is well-defined; the golden's Python reference uses the same
    // NEG_INF sentinel constant ~-1e30).
    const TolerancedCellDelta V_delta = compute_toleranced_cell_delta(
        match_alpha.data(), golden_V.data(), lq + 1, lt + 1, tol.matrix_abs,
        tol.matrix_rel);
    const bool stage4_ok = V_delta.all_within;
    std::printf(
        "  stage 4 V_match_alpha   : %s max_abs=%.3e at (%zu,%zu) "
        "hikoboshi=%.4f pytorch=%.4f rel=%.3e bound=%.3e\n",
        stage4_ok ? "PASS" : "FAIL",
        static_cast<double>(V_delta.max_abs.max_abs),
        V_delta.max_abs.worst_i, V_delta.max_abs.worst_j,
        static_cast<double>(V_delta.max_abs.hikoboshi),
        static_cast<double>(V_delta.max_abs.pytorch),
        static_cast<double>(V_delta.rel_at_max_abs),
        static_cast<double>(V_delta.bound_at_max_abs));
    if (!stage4_ok) {
      std::printf(
          "    worst tolerance excess=%.3e at (%zu,%zu) diff=%.3e "
          "bound=%.3e rel=%.3e hikoboshi=%.4f pytorch=%.4f\n",
          static_cast<double>(V_delta.worst_excess),
          V_delta.worst_excess_i, V_delta.worst_excess_j,
          static_cast<double>(V_delta.worst_excess_diff),
          static_cast<double>(V_delta.worst_excess_bound),
          static_cast<double>(V_delta.worst_excess_rel),
          static_cast<double>(V_delta.worst_excess_hikoboshi),
          static_cast<double>(V_delta.worst_excess_pytorch));
    }
    if (!stage4_ok && !any_failed) {
      any_failed = true;
      first_failing_stage = 4;
      first_failing_pair = pair_id;
    }

    // Stage 5: M_matrix = match_beta backward.
    const CellDelta M_delta = compute_cell_delta(
        match_beta.data(), golden_M.data(), lq + 1, lt + 1);
    const bool stage5_ok = M_delta.max_abs <= tol.matrix_abs;
    std::printf(
        "  stage 5 M_match_beta    : %s max_abs=%.3e at (%zu,%zu) "
        "hikoboshi=%.4f pytorch=%.4f\n",
        stage5_ok ? "PASS" : "FAIL", static_cast<double>(M_delta.max_abs),
        M_delta.worst_i, M_delta.worst_j,
        static_cast<double>(M_delta.hikoboshi),
        static_cast<double>(M_delta.pytorch));
    if (!stage5_ok && !any_failed) {
      any_failed = true;
      first_failing_stage = 5;
      first_failing_pair = pair_id;
    }

    // Stage 6: posterior (kernel output) vs orihime marginals.
    const CellDelta post_delta = compute_cell_delta(
        hiko_posterior.data(), golden_posterior.data(), lq, lt);
    const bool stage6_ok = post_delta.max_abs <= tol.matrix_abs;
    std::printf(
        "  stage 6 posterior       : %s max_abs=%.3e at (%zu,%zu) "
        "hikoboshi=%.4f pytorch=%.4f cells>0.5=hiko_values%zu/pt%zu\n",
        stage6_ok ? "PASS" : "FAIL", static_cast<double>(post_delta.max_abs),
        post_delta.worst_i, post_delta.worst_j,
        static_cast<double>(post_delta.hikoboshi),
        static_cast<double>(post_delta.pytorch),
        std::count_if(hiko_posterior.begin(), hiko_posterior.end(),
                      [&](float v) { return v > posterior_threshold; }),
        std::count_if(golden_posterior.begin(), golden_posterior.end(),
                      [&](float v) { return v > posterior_threshold; }));
    if (!stage6_ok && !any_failed) {
      any_failed = true;
      first_failing_stage = 6;
      first_failing_pair = pair_id;
    }

    // Stage 7: path.steps coordinate set (cells with Hikoboshi posterior >
    // threshold). Bit-exact set match against the orihime-derived golden set.
    std::vector<std::pair<std::int32_t, std::int32_t>> hiko_steps;
    hiko_steps.reserve(lq * lt);
    for (std::size_t i = 0; i < lq; ++i) {
      for (std::size_t j = 0; j < lt; ++j) {
        if (hiko_posterior[i * lt + j] > posterior_threshold) {
          hiko_steps.emplace_back(static_cast<std::int32_t>(i),
                                static_cast<std::int32_t>(j));
        }
      }
    }
    std::sort(hiko_steps.begin(), hiko_steps.end());
    const bool stage7_ok =
        hiko_steps.size() == golden_steps.size() &&
        std::equal(hiko_steps.begin(), hiko_steps.end(), golden_steps.begin());
    std::printf(
        "  stage 7 path_steps      : %s hikoboshi=%zu cells, pytorch=%zu cells\n",
        stage7_ok ? "PASS" : "FAIL", hiko_steps.size(), golden_steps.size());
    if (!stage7_ok && !any_failed) {
      // Print up to 5 mismatched coordinates to help diagnose.
      std::size_t mismatches_printed = 0;
      std::size_t i_pf = 0;
      std::size_t i_gt = 0;
      while (i_pf < hiko_steps.size() && i_gt < golden_steps.size() &&
             mismatches_printed < 5) {
        if (hiko_steps[i_pf] == golden_steps[i_gt]) {
          ++i_pf;
          ++i_gt;
          continue;
        }
        if (hiko_steps[i_pf] < golden_steps[i_gt]) {
          std::printf("    + hikoboshi-only (%d, %d)\n", hiko_steps[i_pf].first,
                      hiko_steps[i_pf].second);
          ++i_pf;
        } else {
          std::printf("    - pytorch-only (%d, %d)\n", golden_steps[i_gt].first,
                      golden_steps[i_gt].second);
          ++i_gt;
        }
        ++mismatches_printed;
      }
      any_failed = true;
      first_failing_stage = 7;
      first_failing_pair = pair_id;
    }
  }

  if (any_failed) {
    std::fprintf(
        stderr,
        "esm2_softsw_pytorch_parity: FAILED on stage %d (%s) for pair %s. "
        "Dispatch hint: %s -> fe5 scope.\n",
        first_failing_stage, stage_label(first_failing_stage),
        first_failing_pair.c_str(),
        stage_dispatch_hint(first_failing_stage));
    return 1;
  }
  std::printf(
      "esm2_softsw_pytorch_parity: all 8 stages PASS on all 3 fe1 lead pairs "
      "(mode=%s). Per-stage parity is locked; fe5 dispatch should NOT be D1.\n",
      tol.label);
  return 0;
}
