// Soft-SW posterior PyTorch parity (fe1 diagnostic).
//
// Loads `tests/cpp/data/softsw_posterior_goldens.npz` (generated by
// `scripts/softsw_pytorch_goldens.py`) and runs Hikoboshi's
// `soft_smith_waterman_scalar` kernel directly on the per-pair
// `sim_matrix` fixtures using the trained gap parameters / temperature
// stored in the npz. Compares the kernel's `posteriors` and
// `log_partition` element-by-element against the orihime reference values
// captured from `orihime.soft_sw_affine(... lengths=[[Lq, Lt]])`.
//
// This test is the fe1 deliverable. Its purpose is to lock the
// divergence between Hikoboshi's soft-SW posterior and PyTorch's
// `result.alignment` on real ESM2-derived score matrices so fe2 can fix
// the kernel against a stable expectation. The packet constraint is
// explicit: do NOT relax the tolerance to make this test pass; the
// expected outcome at fe1 land time is FAIL with a concrete diagnostic.
// fe2 removes the `should_fail: true` marker once the kernel matches.
//
// On failure (the expected fe1 outcome) the test prints:
//   - per-pair posterior max-abs delta + (i, j) coordinate
//   - per-pair top-10 worst cells with (Hikoboshi, PyTorch) pair values
//   - per-pair log_partition delta
//   - per-pair row-sum and col-sum totals (Hikoboshi vs PyTorch) so the
//     reader can bisect which marginal (if any) matches
//   - per-pair count of zero-vs-non-zero agreement to flag pure
//     scale/normalization differences

#include <hikoboshi/primitives/alignment/smith_waterman.hpp>

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace hiko_p = hikoboshi::primitives::alignment;

namespace {

[[noreturn]] void fail(const std::string& detail) {
  std::fprintf(stderr, "softsw_posterior_pytorch_parity: %s\n", detail.c_str());
  std::exit(1);
}

// === Minimal ZIP_STORED NPZ reader ========================================
// Mirrors the reader in `tests/cpp/esm2_pytorch_real_parity.cpp` and only
// supports ZIP_STORED + ZIP64 because that is what `numpy.savez` emits.

struct NpyEntry {
  std::string dtype;
  std::vector<std::size_t> shape;
  std::vector<unsigned char> data;
};

std::uint16_t read_u16_le(const unsigned char* bytes) noexcept {
  return static_cast<std::uint16_t>(bytes[0]) |
         (static_cast<std::uint16_t>(bytes[1]) << 8);
}

std::uint32_t read_u32_le(const unsigned char* bytes) noexcept {
  return static_cast<std::uint32_t>(bytes[0]) |
         (static_cast<std::uint32_t>(bytes[1]) << 8) |
         (static_cast<std::uint32_t>(bytes[2]) << 16) |
         (static_cast<std::uint32_t>(bytes[3]) << 24);
}

std::uint64_t read_u64_le(const unsigned char* bytes) noexcept {
  std::uint64_t lo = read_u32_le(bytes);
  std::uint64_t hi = read_u32_le(bytes + 4);
  return lo | (hi << 32);
}

std::string strip_quotes(std::string_view value) {
  while (!value.empty() && (value.front() == ' ' || value.front() == '\t')) {
    value.remove_prefix(1);
  }
  while (!value.empty() && (value.back() == ' ' || value.back() == '\t')) {
    value.remove_suffix(1);
  }
  if (value.size() >= 2 && (value.front() == '\'' || value.front() == '"') &&
      value.back() == value.front()) {
    return std::string{value.substr(1, value.size() - 2)};
  }
  return std::string{value};
}

std::string find_string_field(const std::string& header,
                              const std::string& key) {
  const std::string needle = "'" + key + "':";
  const std::size_t pos = header.find(needle);
  if (pos == std::string::npos) {
    return std::string{};
  }
  const std::size_t value_start = pos + needle.size();
  std::size_t value_end = header.find(',', value_start);
  if (value_end == std::string::npos) {
    value_end = header.find('}', value_start);
  }
  if (value_end == std::string::npos) {
    return std::string{};
  }
  return strip_quotes(std::string_view{header}.substr(
      value_start, value_end - value_start));
}

std::vector<std::size_t> parse_shape_field(const std::string& header) {
  const std::string needle = "'shape':";
  const std::size_t pos = header.find(needle);
  if (pos == std::string::npos) {
    return {};
  }
  const std::size_t paren_open = header.find('(', pos);
  const std::size_t paren_close = header.find(')', paren_open);
  if (paren_open == std::string::npos || paren_close == std::string::npos ||
      paren_close <= paren_open) {
    return {};
  }
  std::string body = header.substr(paren_open + 1, paren_close - paren_open - 1);
  std::vector<std::size_t> dims;
  std::string token;
  for (char c : body) {
    if (c == ',' || c == ' ' || c == '\t') {
      if (!token.empty()) {
        dims.push_back(static_cast<std::size_t>(std::stoull(token)));
        token.clear();
      }
    } else {
      token.push_back(c);
    }
  }
  if (!token.empty()) {
    dims.push_back(static_cast<std::size_t>(std::stoull(token)));
  }
  return dims;
}

NpyEntry parse_npy(const unsigned char* bytes, std::size_t size) {
  if (size < 10) {
    fail("npy entry truncated below magic+header-len");
  }
  static const unsigned char kMagic[] = {0x93, 'N', 'U', 'M', 'P', 'Y'};
  if (std::memcmp(bytes, kMagic, sizeof(kMagic)) != 0) {
    fail("npy entry has wrong magic");
  }
  const std::uint8_t major = bytes[6];
  std::size_t header_offset = 0;
  std::size_t header_len = 0;
  if (major == 1) {
    header_len = read_u16_le(bytes + 8);
    header_offset = 10;
  } else if (major == 2 || major == 3) {
    if (size < 12) {
      fail("npy v2+ entry truncated");
    }
    header_len = read_u32_le(bytes + 8);
    header_offset = 12;
  } else {
    fail("npy entry has unsupported major version");
  }
  if (header_offset + header_len > size) {
    fail("npy header runs past entry boundary");
  }
  std::string header(reinterpret_cast<const char*>(bytes + header_offset),
                     header_len);
  NpyEntry entry{};
  entry.dtype = find_string_field(header, "descr");
  if (entry.dtype.empty()) {
    fail("npy header missing descr field");
  }
  const std::string fortran = find_string_field(header, "fortran_order");
  if (!fortran.empty() && fortran != "False") {
    fail("npy entry must be C-order");
  }
  entry.shape = parse_shape_field(header);
  const std::size_t data_offset = header_offset + header_len;
  const std::size_t data_bytes = size - data_offset;
  entry.data.assign(bytes + data_offset, bytes + data_offset + data_bytes);
  return entry;
}

void read_npz(const std::filesystem::path& path,
              std::vector<std::pair<std::string, NpyEntry>>& out_entries) {
  std::ifstream in(path, std::ios::binary | std::ios::ate);
  if (!in) {
    fail("could not open npz fixture: " + path.string());
  }
  const std::streamsize size = in.tellg();
  in.seekg(0, std::ios::beg);
  std::vector<unsigned char> bytes(static_cast<std::size_t>(size));
  if (!in.read(reinterpret_cast<char*>(bytes.data()),
               static_cast<std::streamsize>(bytes.size()))) {
    fail("failed reading npz fixture: " + path.string());
  }
  std::size_t cursor = 0;
  while (cursor + 4 <= bytes.size()) {
    if (read_u32_le(bytes.data() + cursor) != 0x04034b50u) {
      break;
    }
    if (cursor + 30 > bytes.size()) {
      fail("npz local file header truncated");
    }
    const std::uint16_t method = read_u16_le(bytes.data() + cursor + 8);
    if (method != 0) {
      fail("npz fixture must use ZIP_STORED (method=0)");
    }
    std::uint64_t compressed_size =
        read_u32_le(bytes.data() + cursor + 18);
    std::uint64_t uncompressed_size =
        read_u32_le(bytes.data() + cursor + 22);
    const std::uint16_t name_len = read_u16_le(bytes.data() + cursor + 26);
    const std::uint16_t extra_len = read_u16_le(bytes.data() + cursor + 28);
    const std::size_t header_size =
        30 + static_cast<std::size_t>(name_len) + extra_len;
    if (cursor + header_size > bytes.size()) {
      fail("npz local file header + name + extra exceeds archive size");
    }
    if (compressed_size == 0xFFFFFFFFull || uncompressed_size == 0xFFFFFFFFull) {
      const unsigned char* extra = bytes.data() + cursor + 30 + name_len;
      std::size_t extra_pos = 0;
      bool found_zip64 = false;
      while (extra_pos + 4 <= static_cast<std::size_t>(extra_len)) {
        const std::uint16_t tag = read_u16_le(extra + extra_pos);
        const std::uint16_t data_size = read_u16_le(extra + extra_pos + 2);
        if (extra_pos + 4 + data_size > static_cast<std::size_t>(extra_len)) {
          break;
        }
        if (tag == 0x0001u) {
          std::size_t inner = 0;
          if (uncompressed_size == 0xFFFFFFFFull && inner + 8 <= data_size) {
            uncompressed_size = read_u64_le(extra + extra_pos + 4 + inner);
            inner += 8;
          }
          if (compressed_size == 0xFFFFFFFFull && inner + 8 <= data_size) {
            compressed_size = read_u64_le(extra + extra_pos + 4 + inner);
            inner += 8;
          }
          found_zip64 = true;
          break;
        }
        extra_pos += 4 + data_size;
      }
      if (!found_zip64) {
        fail("npz local file header marked ZIP64 but lacks a 0x0001 extra");
      }
    }
    if (compressed_size != uncompressed_size) {
      fail("npz fixture has compressed entry where stored is required");
    }
    if (cursor + header_size + compressed_size > bytes.size()) {
      fail("npz entry runs past archive end");
    }
    std::string name(reinterpret_cast<const char*>(bytes.data() + cursor + 30),
                     name_len);
    if (name.size() >= 4 &&
        std::string_view{name}.substr(name.size() - 4) == std::string_view{".npy"}) {
      name = name.substr(0, name.size() - 4);
    }
    NpyEntry entry = parse_npy(bytes.data() + cursor + header_size,
                               compressed_size);
    out_entries.emplace_back(std::move(name), std::move(entry));
    cursor += header_size + compressed_size;
  }
  if (out_entries.empty()) {
    fail("npz fixture contained no entries: " + path.string());
  }
}

const NpyEntry* find_entry(
    const std::vector<std::pair<std::string, NpyEntry>>& entries,
    const std::string_view name) noexcept {
  for (const auto& entry : entries) {
    if (entry.first == name) {
      return &entry.second;
    }
  }
  return nullptr;
}

const NpyEntry& require_entry(
    const std::vector<std::pair<std::string, NpyEntry>>& entries,
    const std::string& name) {
  const NpyEntry* entry = find_entry(entries, name);
  if (entry == nullptr) {
    fail("npz fixture missing required entry: " + name);
  }
  return *entry;
}

std::int32_t scalar_i32(const NpyEntry& entry, const std::string& name) {
  if (entry.dtype != "<i4" && entry.dtype != "|i4" && entry.dtype != "i4") {
    fail(name + " must be int32 (dtype <i4)");
  }
  if (entry.data.size() != sizeof(std::int32_t)) {
    fail(name + " must be a scalar (4 bytes)");
  }
  std::int32_t value = 0;
  std::memcpy(&value, entry.data.data(), sizeof(std::int32_t));
  return value;
}

float scalar_f32(const NpyEntry& entry, const std::string& name) {
  if (entry.dtype != "<f4" && entry.dtype != "|f4" && entry.dtype != "f4") {
    fail(name + " must be float32 (dtype <f4)");
  }
  if (entry.data.size() != sizeof(float)) {
    fail(name + " must be a scalar (4 bytes)");
  }
  float value = 0.0F;
  std::memcpy(&value, entry.data.data(), sizeof(float));
  return value;
}

std::vector<float> matrix_f32(const NpyEntry& entry,
                              const std::string& name,
                              std::size_t expected_rows,
                              std::size_t expected_cols) {
  if (entry.dtype != "<f4" && entry.dtype != "|f4" && entry.dtype != "f4") {
    fail(name + " must be float32 (dtype <f4)");
  }
  if (entry.shape.size() != 2 || entry.shape[0] != expected_rows ||
      entry.shape[1] != expected_cols) {
    fail(name + " has unexpected shape; expected (" +
         std::to_string(expected_rows) + ", " + std::to_string(expected_cols) +
         ")");
  }
  const std::size_t count = expected_rows * expected_cols;
  if (entry.data.size() != count * sizeof(float)) {
    fail(name + " byte length does not match shape");
  }
  std::vector<float> values(count);
  std::memcpy(values.data(), entry.data.data(), entry.data.size());
  return values;
}

// === Fixture path resolution ==============================================

std::filesystem::path fixture_path() {
  const char* explicit_path = std::getenv("HIKOBOSHI_SOFTSW_PYTORCH_GOLDENS");
  if (explicit_path != nullptr && *explicit_path != '\0') {
    return std::filesystem::path{explicit_path};
  }
  const char* source_root = std::getenv("HIKOBOSHI_SOURCE_ROOT");
  if (source_root != nullptr && *source_root != '\0') {
    return std::filesystem::path{source_root} / "tests" / "cpp" / "data" /
           "softsw_posterior_goldens.npz";
  }
  return std::filesystem::path{"tests/cpp/data/softsw_posterior_goldens.npz"};
}

// === Kernel execution + comparison =======================================

struct PairFixture {
  std::string pair_id;
  std::size_t lq = 0;
  std::size_t lt = 0;
  std::vector<float> sim_matrix;       // [lq * lt]
  std::vector<float> golden_posterior; // [lq * lt]
  float golden_log_partition = 0.0F;
};

PairFixture load_pair(
    const std::vector<std::pair<std::string, NpyEntry>>& entries,
    std::size_t pair_index) {
  const std::string prefix = "pair_" + std::to_string(pair_index) + "_";
  const std::string id_key = prefix + "id";
  const std::string lq_key = prefix + "lq";
  const std::string lt_key = prefix + "lt";
  const std::string log_key = prefix + "log_partition";
  const std::string sim_key = prefix + "sim_matrix";
  const std::string post_key = prefix + "posterior";
  const NpyEntry& id_entry = require_entry(entries, id_key);
  const NpyEntry& lq_entry = require_entry(entries, lq_key);
  const NpyEntry& lt_entry = require_entry(entries, lt_key);
  const NpyEntry& log_entry = require_entry(entries, log_key);
  const NpyEntry& sim_entry = require_entry(entries, sim_key);
  const NpyEntry& post_entry = require_entry(entries, post_key);

  PairFixture pair{};
  // numpy stores `<U` strings as UTF-32 LE (4 bytes per code point); these
  // pair ids are pure ASCII so take every fourth byte and stop at the
  // first padding null.
  if (id_entry.dtype.size() >= 2 && id_entry.dtype[1] == 'U') {
    for (std::size_t k = 0; k + 4 <= id_entry.data.size(); k += 4) {
      const unsigned char ch = id_entry.data[k];
      if (ch == 0u) break;
      pair.pair_id.push_back(static_cast<char>(ch));
    }
  } else {
    pair.pair_id =
        std::string(reinterpret_cast<const char*>(id_entry.data.data()),
                    id_entry.data.size());
    while (!pair.pair_id.empty() && pair.pair_id.back() == '\0') {
      pair.pair_id.pop_back();
    }
  }
  pair.lq = static_cast<std::size_t>(scalar_i32(lq_entry, lq_key));
  pair.lt = static_cast<std::size_t>(scalar_i32(lt_entry, lt_key));
  pair.golden_log_partition = scalar_f32(log_entry, log_key);
  pair.sim_matrix = matrix_f32(sim_entry, sim_key, pair.lq, pair.lt);
  pair.golden_posterior =
      matrix_f32(post_entry, post_key, pair.lq, pair.lt);
  return pair;
}

struct PosteriorComparison {
  float max_abs = 0.0F;
  std::size_t worst_i = 0;
  std::size_t worst_j = 0;
  float worst_hikoboshi = 0.0F;
  float worst_pytorch = 0.0F;
  double hikoboshi_sum = 0.0;
  double pytorch_sum = 0.0;
  std::size_t hikoboshi_above_half = 0;
  std::size_t pytorch_above_half = 0;
  std::size_t zero_both = 0;
  std::size_t zero_only_hikoboshi = 0;
  std::size_t zero_only_pytorch = 0;
  std::size_t nonzero_both = 0;
  double scale_ratio_sum = 0.0;
  std::size_t scale_ratio_count = 0;
};

PosteriorComparison compare_posteriors(const PairFixture& pair,
                                       const std::vector<float>& hiko_values) {
  PosteriorComparison report{};
  constexpr float kZeroTol = 1e-7F;
  for (std::size_t i = 0; i < pair.lq; ++i) {
    for (std::size_t j = 0; j < pair.lt; ++j) {
      const std::size_t cell = i * pair.lt + j;
      const float p = hiko_values[cell];
      const float g = pair.golden_posterior[cell];
      const float diff = std::fabs(p - g);
      if (diff > report.max_abs) {
        report.max_abs = diff;
        report.worst_i = i;
        report.worst_j = j;
        report.worst_hikoboshi = p;
        report.worst_pytorch = g;
      }
      report.hikoboshi_sum += static_cast<double>(p);
      report.pytorch_sum += static_cast<double>(g);
      if (p > 0.5F) ++report.hikoboshi_above_half;
      if (g > 0.5F) ++report.pytorch_above_half;
      const bool zero_p = std::fabs(p) <= kZeroTol;
      const bool zero_g = std::fabs(g) <= kZeroTol;
      if (zero_p && zero_g) {
        ++report.zero_both;
      } else if (zero_p) {
        ++report.zero_only_hikoboshi;
      } else if (zero_g) {
        ++report.zero_only_pytorch;
      } else {
        ++report.nonzero_both;
        if (g > 1e-3F) {
          report.scale_ratio_sum += static_cast<double>(p) /
                                    static_cast<double>(g);
          ++report.scale_ratio_count;
        }
      }
    }
  }
  return report;
}

struct WorstCell {
  std::size_t i;
  std::size_t j;
  float hikoboshi;
  float pytorch;
  float abs_delta;
};

std::vector<WorstCell> collect_top10_worst_cells(const PairFixture& pair,
                                                 const std::vector<float>& hiko_values) {
  std::vector<WorstCell> cells;
  cells.reserve(pair.lq * pair.lt);
  for (std::size_t i = 0; i < pair.lq; ++i) {
    for (std::size_t j = 0; j < pair.lt; ++j) {
      const std::size_t cell = i * pair.lt + j;
      WorstCell entry{};
      entry.i = i;
      entry.j = j;
      entry.hikoboshi = hiko_values[cell];
      entry.pytorch = pair.golden_posterior[cell];
      entry.abs_delta = std::fabs(entry.hikoboshi - entry.pytorch);
      cells.push_back(entry);
    }
  }
  std::sort(cells.begin(), cells.end(),
            [](const WorstCell& a, const WorstCell& b) {
              return a.abs_delta > b.abs_delta;
            });
  if (cells.size() > 10) {
    cells.resize(10);
  }
  return cells;
}

// === Optional: Hikoboshi per-row / per-col marginals ========================
// PyTorch's `result.alignment` is documented as the soft alignment matrix
// (marginals). Hikoboshi's `output.posteriors` is the per-cell match-state
// posterior. Comparing row-sums and col-sums tells the reader at a glance
// whether the two semantics differ by a row- or column-stochastic
// normalization factor.

std::vector<float> row_sums(const std::vector<float>& matrix,
                            std::size_t lq, std::size_t lt) {
  std::vector<float> sums(lq, 0.0F);
  for (std::size_t i = 0; i < lq; ++i) {
    for (std::size_t j = 0; j < lt; ++j) {
      sums[i] += matrix[i * lt + j];
    }
  }
  return sums;
}

std::vector<float> col_sums(const std::vector<float>& matrix,
                            std::size_t lq, std::size_t lt) {
  std::vector<float> sums(lt, 0.0F);
  for (std::size_t i = 0; i < lq; ++i) {
    for (std::size_t j = 0; j < lt; ++j) {
      sums[j] += matrix[i * lt + j];
    }
  }
  return sums;
}

struct MarginalSummary {
  float hiko_max = 0.0F;
  float pt_max = 0.0F;
  double hiko_mean = 0.0;
  double pt_mean = 0.0;
};

MarginalSummary summarize(const std::vector<float>& hiko_marginals,
                          const std::vector<float>& pt_marginals) {
  MarginalSummary out{};
  for (std::size_t i = 0; i < hiko_marginals.size(); ++i) {
    out.hiko_max = std::max(out.hiko_max, hiko_marginals[i]);
    out.pt_max = std::max(out.pt_max, pt_marginals[i]);
    out.hiko_mean += static_cast<double>(hiko_marginals[i]);
    out.pt_mean += static_cast<double>(pt_marginals[i]);
  }
  if (!hiko_marginals.empty()) {
    out.hiko_mean /= static_cast<double>(hiko_marginals.size());
    out.pt_mean /= static_cast<double>(pt_marginals.size());
  }
  return out;
}

}  // namespace

int main() {
  const std::filesystem::path fixture = fixture_path();
  std::vector<std::pair<std::string, NpyEntry>> entries;
  read_npz(fixture, entries);

  const std::int32_t pair_count =
      scalar_i32(require_entry(entries, "pair_count"), "pair_count");
  const float gap_open =
      scalar_f32(require_entry(entries, "gap_open"), "gap_open");
  const float gap_ext =
      scalar_f32(require_entry(entries, "gap_ext"), "gap_ext");
  const float temperature =
      scalar_f32(require_entry(entries, "temperature"), "temperature");
  if (pair_count <= 0) {
    fail("npz fixture must contain at least one pair");
  }

  std::printf(
      "softsw_posterior_pytorch_parity: pairs=%d gap_open=%.6f gap_ext=%.6f "
      "temperature=%.6f\n",
      pair_count, static_cast<double>(gap_open), static_cast<double>(gap_ext),
      static_cast<double>(temperature));

  const float tolerance = 1.0e-4F;  // public fast-mode parity contract
  bool any_failed = false;

  for (std::int32_t pair_index = 0; pair_index < pair_count; ++pair_index) {
    PairFixture pair =
        load_pair(entries, static_cast<std::size_t>(pair_index));

    const std::size_t score_cells = pair.lq * pair.lt;
    const std::size_t workspace_cells = (pair.lq + 1U) * (pair.lt + 1U);

    std::vector<float> match_alpha(workspace_cells, 0.0F);
    std::vector<float> insert_alpha(workspace_cells, 0.0F);
    std::vector<float> delete_alpha(workspace_cells, 0.0F);
    std::vector<float> match_beta(workspace_cells, 0.0F);
    std::vector<float> insert_beta(workspace_cells, 0.0F);
    std::vector<float> delete_beta(workspace_cells, 0.0F);
    std::vector<float> hiko_posteriors(score_cells, 0.0F);

    hiko_p::SoftSmithWatermanScalarRequest request{};
    request.scores = pair.sim_matrix.data();
    request.query_length = pair.lq;
    request.target_length = pair.lt;
    request.gap_open = gap_open;
    request.gap_extension = gap_ext;
    request.temperature = temperature;
    request.match_workspace = match_alpha.data();
    request.insert_workspace = insert_alpha.data();
    request.delete_workspace = delete_alpha.data();
    request.workspace_cells = workspace_cells;
    request.match_grad_workspace = match_beta.data();
    request.insert_grad_workspace = insert_beta.data();
    request.delete_grad_workspace = delete_beta.data();

    hiko_p::SoftSmithWatermanScalarOutput output{};
    output.posteriors = hiko_posteriors.data();
    output.log_partition = 0.0F;

    hiko_p::soft_smith_waterman_scalar(request, output);

    const PosteriorComparison cmp = compare_posteriors(pair, hiko_posteriors);
    const std::vector<WorstCell> top10 =
        collect_top10_worst_cells(pair, hiko_posteriors);

    const std::vector<float> hiko_row = row_sums(hiko_posteriors, pair.lq, pair.lt);
    const std::vector<float> pt_row =
        row_sums(pair.golden_posterior, pair.lq, pair.lt);
    const std::vector<float> hiko_col = col_sums(hiko_posteriors, pair.lq, pair.lt);
    const std::vector<float> pt_col =
        col_sums(pair.golden_posterior, pair.lq, pair.lt);
    const MarginalSummary row_summary = summarize(hiko_row, pt_row);
    const MarginalSummary col_summary = summarize(hiko_col, pt_col);

    const float log_partition_delta =
        std::fabs(output.log_partition - pair.golden_log_partition);
    const double scale_ratio_mean =
        cmp.scale_ratio_count > 0
            ? cmp.scale_ratio_sum / static_cast<double>(cmp.scale_ratio_count)
            : 0.0;

    std::printf(
        "--- pair %d: %s lq=%zu lt=%zu ---\n"
        "  log_partition: hikoboshi=%.6f pytorch=%.6f abs_delta=%.6e\n"
        "  posterior max_abs=%.6e at (%zu, %zu) hikoboshi=%.6f pytorch=%.6f\n"
        "  totals: hikoboshi_sum=%.6f pytorch_sum=%.6f "
        "(cells>0.5 hikoboshi=%zu pytorch=%zu)\n"
        "  zeros: both=%zu only_hikoboshi=%zu only_pytorch=%zu nonzero_both=%zu "
        "scale_ratio_mean=%.6f (n=%zu)\n"
        "  row_sums: hikoboshi max=%.4f mean=%.4f | pytorch max=%.4f mean=%.4f\n"
        "  col_sums: hikoboshi max=%.4f mean=%.4f | pytorch max=%.4f mean=%.4f\n"
        "  top-10 worst cells (i, j, hikoboshi, pytorch, |delta|):\n",
        pair_index, pair.pair_id.c_str(), pair.lq, pair.lt,
        static_cast<double>(output.log_partition),
        static_cast<double>(pair.golden_log_partition),
        static_cast<double>(log_partition_delta),
        static_cast<double>(cmp.max_abs), cmp.worst_i, cmp.worst_j,
        static_cast<double>(cmp.worst_hikoboshi),
        static_cast<double>(cmp.worst_pytorch),
        cmp.hikoboshi_sum, cmp.pytorch_sum, cmp.hikoboshi_above_half,
        cmp.pytorch_above_half, cmp.zero_both, cmp.zero_only_hikoboshi,
        cmp.zero_only_pytorch, cmp.nonzero_both, scale_ratio_mean,
        cmp.scale_ratio_count,
        static_cast<double>(row_summary.hiko_max), row_summary.hiko_mean,
        static_cast<double>(row_summary.pt_max), row_summary.pt_mean,
        static_cast<double>(col_summary.hiko_max), col_summary.hiko_mean,
        static_cast<double>(col_summary.pt_max), col_summary.pt_mean);
    for (const WorstCell& cell : top10) {
      std::printf("    (%zu, %zu) hikoboshi=%.6f pytorch=%.6f |delta|=%.6e\n",
                  cell.i, cell.j, static_cast<double>(cell.hikoboshi),
                  static_cast<double>(cell.pytorch),
                  static_cast<double>(cell.abs_delta));
    }

    if (!(cmp.max_abs <= tolerance)) {
      any_failed = true;
    }
  }

  if (any_failed) {
    std::fprintf(
        stderr,
        "softsw_posterior_pytorch_parity: Hikoboshi posterior diverges from "
        "orihime.soft_sw_affine beyond fast-mode tolerance %.6e. This is the "
        "fe1 diagnostic outcome; the bisection clues above feed fe2's fix in "
        "cpp/primitives/alignment/soft_smith_waterman_scalar.cpp.\n",
        static_cast<double>(tolerance));
    return 1;
  }
  return 0;
}
