// End-to-end pairwise smoke for the hikoboshi-esm2-8m sequence-input route.
//
// Drives `Engine::pairwise(PairwiseSequenceRequest)` with two real
// ~150-residue protein sequences (sperm-whale myoglobin P02185 and human
// ribonuclease-1 P07998) and confirms the encoder + RawDot scoring +
// hard-SW alignment chain produces well-formed output under both the
// fast (default) and strict GEMM parity modes.
//
// Strict-mode bit-parity vs the PyTorch ESM2-8M reference is gated on a
// fixture generated by the `esm2-8m-integration-validate` packet; when
// the fixture is absent the parity check is skipped (matching the
// `sequence_route_parity_tests` pattern). When present, fast-mode max
// abs is bounded by 1e-4 and strict-mode max abs by 1e-5, mirroring the
// published 0.1.0 contract.

#include <hikoboshi/api/engine.hpp>
#include <hikoboshi/weights/provider.hpp>

#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <string>
#include <string_view>
#include <vector>

namespace hiko = hikoboshi::api;
namespace hiko_u = hikoboshi::universal;
namespace hiko_w = hikoboshi::weights;

namespace {

void fail(const char* tag) {
  std::fprintf(stderr, "esm2_8m_pairwise_smoke: %s\n", tag);
  std::exit(1);
}

// hikoboshi-esm2-8m compacted 29-row alphabet. Mirrors `esm2_aa_token` in
// `cpp/cli/commands/pairwise.cpp`; Hikoboshi's CLI maintains the same table
// because the api layer cannot reach into the weights TU that owns the
// embedded tokenizer. Drift is caught at packet review.
std::int32_t aa_token(char c) noexcept {
  switch (c) {
    case 'A': return 0;
    case 'R': return 1;
    case 'N': return 2;
    case 'D': return 3;
    case 'C': return 4;
    case 'Q': return 5;
    case 'E': return 6;
    case 'G': return 7;
    case 'H': return 8;
    case 'I': return 9;
    case 'L': return 10;
    case 'K': return 11;
    case 'M': return 12;
    case 'F': return 13;
    case 'P': return 14;
    case 'S': return 15;
    case 'T': return 16;
    case 'W': return 17;
    case 'Y': return 18;
    case 'V': return 19;
    case 'B': return 20;
    case 'U': return 21;
    case 'Z': return 22;
    case 'O': return 23;
    case 'X': return 24;
    default:  return 24;  // unknown -> X
  }
}

std::vector<std::int32_t> tokenize(std::string_view aa) {
  std::vector<std::int32_t> tokens;
  tokens.reserve(aa.size());
  for (char c : aa) {
    if (c >= 'a' && c <= 'z') c = static_cast<char>(c - 'a' + 'A');
    tokens.push_back(aa_token(c));
  }
  return tokens;
}

// Sperm whale myoglobin (UniProt P02185), 153 residues.
constexpr std::string_view kMyoglobin =
    "VLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRFKHLKTEAEMKASED"
    "LKKHGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRHP"
    "GNFGADAQGAMNKALELFRKDIAAKYKELGYQG";

// Human ribonuclease pancreatic (UniProt P07998), 156 residues.
constexpr std::string_view kRibonuclease =
    "MALEKSLVRLLLLVLILLVLGWVQPSLGKESRAKKFQRQHMDSDSSPSSSSTYCNQMMRR"
    "RNMTQGRCKPVNTFVHEPLVDVQNVCFQEKVTCKNGQGNCYKSNSSMHITDCRLTNGSRY"
    "PNCAYRTSPKERHIIVACEGSPYVPVHFDASVEDST";

hiko::Engine make_esm2_engine() {
  const hiko_u::Result<hiko_w::PackageHandle> package =
      hiko_w::default_esm2_8m_package();
  if (package.status.code != hiko_u::StatusCode::Ok) {
    fail("hikoboshi-esm2-8m package handle must be resolvable");
  }
  hiko::EngineConfig config{};
  config.package = package.value;
  return hiko::Engine{config};
}

void check_pairwise(const hiko::Engine& engine,
                    const std::vector<std::int32_t>& q,
                    const std::vector<std::int32_t>& t,
                    const char* label) {
  hiko::PairwiseSequenceRequest request{};
  request.query_token_ids = {q.data(), q.size()};
  request.target_token_ids = {t.data(), t.size()};
  request.mode = hiko::AlignmentMode::Hard;
  const auto result = engine.pairwise(request);
  if (result.status.code != hiko_u::StatusCode::Ok) {
    std::fprintf(stderr,
                 "esm2_8m_pairwise_smoke: pairwise(%s) returned status %d\n",
                 label, static_cast<int>(result.status.code));
    fail("pairwise must succeed");
  }
  if (!(result.value.metrics.raw_sw_score > 0.0)) {
    fail("raw_sw_score must be positive for real homologous-or-similar pair");
  }
  if (result.value.path.aligned_pairs == 0U) {
    fail("alignment must produce at least one aligned pair");
  }
  // Coverage values are fractions in [0, 1] when valid; under the
  // sequence-input route both directions are computed because the
  // alignment cells reference real residue positions.
  const auto& cov_q = result.value.metrics.coverage_query;
  const auto& cov_t = result.value.metrics.coverage_target;
  if (cov_q.valid && !(cov_q.value >= 0.0 && cov_q.value <= 1.0)) {
    fail("coverage_query out of [0, 1]");
  }
  if (cov_t.valid && !(cov_t.value >= 0.0 && cov_t.value <= 1.0)) {
    fail("coverage_target out of [0, 1]");
  }
}

void test_pairwise_self_self() {
  const hiko::Engine engine = make_esm2_engine();
  const auto myo = tokenize(kMyoglobin);
  hiko::PairwiseSequenceRequest request{};
  request.query_token_ids = {myo.data(), myo.size()};
  request.target_token_ids = {myo.data(), myo.size()};
  request.mode = hiko::AlignmentMode::Hard;
  const auto result = engine.pairwise(request);
  if (result.status.code != hiko_u::StatusCode::Ok) {
    fail("self-self pairwise must succeed");
  }
  if (result.value.path.aligned_pairs != myo.size()) {
    fail("self-self pairwise on hard SW must align every residue");
  }
  if (!(result.value.metrics.raw_sw_score > 0.0)) {
    fail("self-self raw_sw_score must be positive");
  }
}

void test_pairwise_real_protein_pair() {
  const hiko::Engine engine = make_esm2_engine();
  const auto query = tokenize(kMyoglobin);
  const auto target = tokenize(kRibonuclease);
  check_pairwise(engine, query, target, "myoglobin-vs-ribonuclease");
}

// Optional bit-tight parity vs PyTorch ESM2-8M end-to-end output.
// Skips with exit 0 if the fixture is absent (matches the
// `sequence_route_parity_tests` pattern).
struct PairwiseFixture {
  std::vector<std::int32_t> query_tokens;
  std::vector<std::int32_t> target_tokens;
  double expected_raw_score = 0.0;
  std::uint32_t expected_aligned_pairs = 0;
};

bool load_pairwise_fixture(const std::string& path, PairwiseFixture& out) {
  std::ifstream in(path, std::ios::binary);
  if (!in) {
    return false;
  }
  std::uint32_t magic = 0;
  in.read(reinterpret_cast<char*>(&magic), sizeof(magic));
  if (!in || magic != 0xE5C2'8501u) {
    return false;
  }
  std::uint32_t qlen = 0;
  std::uint32_t tlen = 0;
  in.read(reinterpret_cast<char*>(&qlen), sizeof(qlen));
  in.read(reinterpret_cast<char*>(&tlen), sizeof(tlen));
  if (!in || qlen == 0 || tlen == 0) {
    return false;
  }
  out.query_tokens.assign(qlen, 0);
  out.target_tokens.assign(tlen, 0);
  for (std::uint32_t i = 0; i < qlen; ++i) {
    std::int32_t token = 0;
    in.read(reinterpret_cast<char*>(&token), sizeof(token));
    if (!in) return false;
    out.query_tokens[i] = token;
  }
  for (std::uint32_t i = 0; i < tlen; ++i) {
    std::int32_t token = 0;
    in.read(reinterpret_cast<char*>(&token), sizeof(token));
    if (!in) return false;
    out.target_tokens[i] = token;
  }
  in.read(reinterpret_cast<char*>(&out.expected_raw_score),
          sizeof(out.expected_raw_score));
  in.read(reinterpret_cast<char*>(&out.expected_aligned_pairs),
          sizeof(out.expected_aligned_pairs));
  return static_cast<bool>(in);
}

std::string fixture_path_from_env() {
  const char* explicit_path =
      std::getenv("HIKOBOSHI_ESM2_PAIRWISE_FIXTURE");
  if (explicit_path != nullptr && *explicit_path != '\0') {
    return std::string{explicit_path};
  }
  const char* source_root = std::getenv("HIKOBOSHI_SOURCE_ROOT");
  if (source_root != nullptr && *source_root != '\0') {
    return std::string{source_root} +
           "/tests/parity/esm2_8m_pytorch/pairwise_fixture.bin";
  }
  return std::string{
      "tests/parity/esm2_8m_pytorch/pairwise_fixture.bin"};
}

float active_score_tolerance() noexcept {
  const char* mode = std::getenv("HIKOBOSHI_GEMM_PARITY_MODE");
  if (mode != nullptr && std::string_view{mode} == "strict") {
    return 1.0e-5F;
  }
  return 1.0e-4F;
}

void test_pytorch_parity_optional() {
  const std::string path = fixture_path_from_env();
  PairwiseFixture fixture{};
  if (!load_pairwise_fixture(path, fixture)) {
    std::fprintf(stderr,
                 "esm2_8m_pairwise_smoke: pytorch parity skipped — fixture "
                 "not present (looked at %s)\n",
                 path.c_str());
    return;
  }
  const hiko::Engine engine = make_esm2_engine();
  hiko::PairwiseSequenceRequest request{};
  request.query_token_ids = {fixture.query_tokens.data(),
                             fixture.query_tokens.size()};
  request.target_token_ids = {fixture.target_tokens.data(),
                              fixture.target_tokens.size()};
  request.mode = hiko::AlignmentMode::Hard;
  const auto result = engine.pairwise(request);
  if (result.status.code != hiko_u::StatusCode::Ok) {
    fail("fixture pairwise must succeed");
  }
  const double diff = std::fabs(static_cast<double>(
      result.value.metrics.raw_sw_score - fixture.expected_raw_score));
  const double tol = static_cast<double>(active_score_tolerance());
  if (diff > tol) {
    std::fprintf(stderr,
                 "esm2_8m_pairwise_smoke: raw_sw_score diff %.6e exceeds "
                 "tolerance %.6e (got %.6f, want %.6f)\n",
                 diff, tol,
                 static_cast<double>(result.value.metrics.raw_sw_score),
                 fixture.expected_raw_score);
    fail("pytorch parity score tolerance breach");
  }
  if (result.value.path.aligned_pairs !=
      static_cast<std::size_t>(fixture.expected_aligned_pairs)) {
    fail("pytorch parity aligned_pairs mismatch");
  }
}

}  // namespace

int main() {
  test_pairwise_self_self();
  test_pairwise_real_protein_pair();
  test_pytorch_parity_optional();
  std::printf("esm2_8m_pairwise_smoke: ok\n");
  return 0;
}
