#!/usr/bin/env python3
"""Generate orihime reference data for soft_smith_waterman_scalar parity tests.

Run with the orihime-verify-mainref env to regenerate the constexpr arrays embedded
in tests/cpp/soft_smith_waterman_scalar_tests.cpp:

    python tests/cpp/support/generate_soft_sw_orihime_reference.py

Output is a self-contained C++ snippet with one record per (Lq, Lt, T) case.
"""

from __future__ import annotations

import argparse
import sys
from typing import Iterable, Sequence

import numpy as np
import torch
import orihime as ori


def fmt_float(value: float) -> str:
    if not np.isfinite(value):
        return "0.0F"
    text = f"{value:.9g}"
    if "." not in text and "e" not in text and "E" not in text:
        text += ".0"
    return text + "F"


def emit_row(values: Iterable[float]) -> str:
    return ", ".join(fmt_float(float(v)) for v in values)


def emit_case(index: int, lq: int, lt: int, gap_open: float, gap_ext: float, temperature: float, seed: int) -> str:
    rng = np.random.default_rng(seed)
    scores = rng.standard_normal(size=(lq, lt)).astype(np.float32)

    score_tensor = torch.from_numpy(scores).unsqueeze(0).contiguous()
    partition_tensor, posteriors_tensor = ori.ops.sw_affine.forward(
        score_tensor,
        float(gap_open),
        float(gap_ext),
        float(temperature),
        None,
    )
    partition = float(partition_tensor[0].item())
    posteriors = posteriors_tensor[0].cpu().numpy().astype(np.float32)

    lines: list[str] = []
    lines.append(f"// case {index}: Lq={lq}, Lt={lt}, T={temperature:g}, gap_open={gap_open:g}, gap_ext={gap_ext:g}, seed={seed}")
    lines.append(f"static constexpr std::size_t kCase{index}Lq = {lq};")
    lines.append(f"static constexpr std::size_t kCase{index}Lt = {lt};")
    lines.append(f"static constexpr float kCase{index}GapOpen = {fmt_float(gap_open)};")
    lines.append(f"static constexpr float kCase{index}GapExt = {fmt_float(gap_ext)};")
    lines.append(f"static constexpr float kCase{index}Temperature = {fmt_float(temperature)};")
    lines.append(f"static constexpr float kCase{index}LogPartition = {fmt_float(partition)};")
    lines.append(f"static const float kCase{index}Scores[{lq * lt}] = {{")
    for i in range(lq):
        row = scores[i]
        lines.append("    " + emit_row(row.tolist()) + ",")
    lines.append("};")
    lines.append(f"static const float kCase{index}Posteriors[{lq * lt}] = {{")
    for i in range(lq):
        row = posteriors[i]
        lines.append("    " + emit_row(row.tolist()) + ",")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main(argv: Sequence[str] = ()) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args(list(argv))

    cases = [
        # (Lq, Lt, gap_open, gap_ext, temperature, seed)
        (10, 10, -1.4, -0.15, 1.0, 1001),
        (10, 10, -1.4, -0.15, 1e-2, 1002),
        (10, 10, -1.4, -0.15, 1e-3, 1003),
        (20, 20, -1.4, -0.15, 1.0, 2001),
        (20, 20, -1.4, -0.15, 1e-2, 2002),
        (20, 20, -1.0, -0.5, 1.0, 2003),
        (50, 50, -1.4, -0.15, 1.0, 3001),
        (50, 50, -1.4, -0.15, 1e-2, 3002),
        (50, 50, -1.4, -0.15, 1e-3, 3003),
        (100, 150, -1.4, -0.15, 1.0, 4001),
        (100, 150, -1.4, -0.15, 1e-2, 4002),
    ]

    out = sys.stdout
    out.write("// Generated by tests/cpp/support/generate_soft_sw_orihime_reference.py\n")
    out.write("// using ori.ops.sw_affine.forward. Do not edit by hand.\n\n")
    for idx, (lq, lt, gap_open, gap_ext, temperature, seed) in enumerate(cases, start=1):
        out.write(emit_case(idx, lq, lt, gap_open, gap_ext, temperature, seed))
    out.write(f"static constexpr std::size_t kCaseCount = {len(cases)};\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
